// 装饰分类配置
// 支持直接指定图片路径，图片应放在 public/images/emojis/ 目录下

import { EmojiCategory } from './emoji-categories';

// 装饰分类配置
export const DECORATION_CATEGORIES: EmojiCategory[] = [
  {
    name: 'Gesture',
    items: [
      { id: 'gesture-1', imagePath: '/images/emojis/Gesture/Palm-down hand.png', name: 'Palm-down hand' },
      { id: 'gesture-2', imagePath: '/images/emojis/Gesture/☝️ Index finger pointing up.png', name: '☝️ Index finger pointing up' },
      { id: 'gesture-3', imagePath: '/images/emojis/Gesture/✊ Raised fist.png', name: '✊ Raised fist' },
      { id: 'gesture-4', imagePath: '/images/emojis/Gesture/✋ Raised hand.png', name: '✋ Raised hand' },
      { id: 'gesture-5', imagePath: '/images/emojis/Gesture/✌️ Peace hand sign.png', name: '✌️ Peace hand sign' },
      { id: 'gesture-6', imagePath: '/images/emojis/Gesture/✍️ Writing hand.png', name: '✍️ Writing hand' },
      { id: 'gesture-7', imagePath: '/images/emojis/Gesture/👀 Eyes.png', name: '👀 Eyes' },
      { id: 'gesture-8', imagePath: '/images/emojis/Gesture/👁 Eye.png', name: '👁 Eye' },
      { id: 'gesture-9', imagePath: '/images/emojis/Gesture/👂 Ear.png', name: '👂 Ear' },
      { id: 'gesture-10', imagePath: '/images/emojis/Gesture/👃 Nose.png', name: '👃 Nose' },
      { id: 'gesture-11', imagePath: '/images/emojis/Gesture/👄 Mouth.png', name: '👄 Mouth' },
      { id: 'gesture-12', imagePath: '/images/emojis/Gesture/👅 Tongue.png', name: '👅 Tongue' },
      { id: 'gesture-13', imagePath: '/images/emojis/Gesture/👆 Backhand index finger pointing up.png', name: '👆 Backhand index finger pointing up' },
      { id: 'gesture-14', imagePath: '/images/emojis/Gesture/👇 Backhand index finger pointing down.png', name: '👇 Backhand index finger pointing down' },
      { id: 'gesture-15', imagePath: '/images/emojis/Gesture/👈 Backhand index finger pointing left.png', name: '👈 Backhand index finger pointing left' },
      { id: 'gesture-16', imagePath: '/images/emojis/Gesture/👉 Backhand index finger pointing right.png', name: '👉 Backhand index finger pointing right' },
      { id: 'gesture-17', imagePath: '/images/emojis/Gesture/👊 Closed fist.png', name: '👊 Closed fist' },
      { id: 'gesture-18', imagePath: '/images/emojis/Gesture/👋 Waving hand.png', name: '👋 Waving hand' },
      { id: 'gesture-19', imagePath: '/images/emojis/Gesture/👌 OK hand sign.png', name: '👌 OK hand sign' },
      { id: 'gesture-20', imagePath: '/images/emojis/Gesture/👍 Thumbs up.png', name: '👍 Thumbs up' },
      { id: 'gesture-21', imagePath: '/images/emojis/Gesture/👎 Thumbs down.png', name: '👎 Thumbs down' },
      { id: 'gesture-22', imagePath: '/images/emojis/Gesture/👏 Clapping hands.png', name: '👏 Clapping hands' },
      { id: 'gesture-23', imagePath: '/images/emojis/Gesture/👐 Open hands.png', name: '👐 Open hands' },
      { id: 'gesture-24', imagePath: '/images/emojis/Gesture/👣 Footprints.png', name: '👣 Footprints' },
      { id: 'gesture-25', imagePath: '/images/emojis/Gesture/👤 Silhouette of person.png', name: '👤 Silhouette of person' },
      { id: 'gesture-26', imagePath: '/images/emojis/Gesture/👥 Silhouette of two people.png', name: '👥 Silhouette of two people' },
      { id: 'gesture-27', imagePath: '/images/emojis/Gesture/💄 Lipstick.png', name: '💄 Lipstick' },
      { id: 'gesture-28', imagePath: '/images/emojis/Gesture/💋 Kiss mark.png', name: '💋 Kiss mark' },
      { id: 'gesture-29', imagePath: '/images/emojis/Gesture/💪 Flexed bicep.png', name: '💪 Flexed bicep' },
      { id: 'gesture-30', imagePath: '/images/emojis/Gesture/🖐 Raised hand with fingers splayed.png', name: '🖐 Raised hand with fingers splayed' },
      { id: 'gesture-31', imagePath: '/images/emojis/Gesture/🖕 Middle finger.png', name: '🖕 Middle finger' },
      { id: 'gesture-32', imagePath: '/images/emojis/Gesture/🖖 Hand with fingers split between middle and ring fingers.png', name: '🖖 Hand with fingers split between middle and ring fingers' },
      { id: 'gesture-33', imagePath: '/images/emojis/Gesture/🗣 Speaking silhouette head.png', name: '🗣 Speaking silhouette head' },
      { id: 'gesture-34', imagePath: '/images/emojis/Gesture/🙌 Hands raised in celebration.png', name: '🙌 Hands raised in celebration' },
      { id: 'gesture-35', imagePath: '/images/emojis/Gesture/🙏 Hands pressed together.png', name: '🙏 Hands pressed together' },
      { id: 'gesture-36', imagePath: '/images/emojis/Gesture/🤌 Pinched fingers.png', name: '🤌 Pinched fingers' },
      { id: 'gesture-37', imagePath: '/images/emojis/Gesture/🤏 Pinching hand.png', name: '🤏 Pinching hand' },
      { id: 'gesture-38', imagePath: '/images/emojis/Gesture/🤘 Sign of the horns.png', name: '🤘 Sign of the horns' },
      { id: 'gesture-39', imagePath: '/images/emojis/Gesture/🤙 Call me hand sign.png', name: '🤙 Call me hand sign' },
      { id: 'gesture-40', imagePath: '/images/emojis/Gesture/🤚 Back of hand.png', name: '🤚 Back of hand' },
      { id: 'gesture-41', imagePath: '/images/emojis/Gesture/🤛 Left-facing fist.png', name: '🤛 Left-facing fist' },
      { id: 'gesture-42', imagePath: '/images/emojis/Gesture/🤜 Right-facing fist.png', name: '🤜 Right-facing fist' },
      { id: 'gesture-43', imagePath: '/images/emojis/Gesture/🤝 Handshake.png', name: '🤝 Handshake' },
      { id: 'gesture-44', imagePath: '/images/emojis/Gesture/🤞 Fingers crossed.png', name: '🤞 Fingers crossed' },
      { id: 'gesture-45', imagePath: '/images/emojis/Gesture/🤟 Love-you gesture.png', name: '🤟 Love-you gesture' },
      { id: 'gesture-46', imagePath: '/images/emojis/Gesture/🤲 Palms together facing up.png', name: '🤲 Palms together facing up' },
      { id: 'gesture-47', imagePath: '/images/emojis/Gesture/🦵 Leg.png', name: '🦵 Leg' },
      { id: 'gesture-48', imagePath: '/images/emojis/Gesture/🦶 Foot.png', name: '🦶 Foot' },
      { id: 'gesture-49', imagePath: '/images/emojis/Gesture/🦷 Tooth.png', name: '🦷 Tooth' },
      { id: 'gesture-50', imagePath: '/images/emojis/Gesture/🦻 Ear with hearing aid.png', name: '🦻 Ear with hearing aid' },
      { id: 'gesture-51', imagePath: '/images/emojis/Gesture/🦾 Mechanical arm.png', name: '🦾 Mechanical arm' },
      { id: 'gesture-52', imagePath: '/images/emojis/Gesture/🦿 Mechanical leg.png', name: '🦿 Mechanical leg' },
      { id: 'gesture-53', imagePath: '/images/emojis/Gesture/🧠 Brain.png', name: '🧠 Brain' },
      { id: 'gesture-54', imagePath: '/images/emojis/Gesture/🫀 Anatomical heart.png', name: '🫀 Anatomical heart' },
      { id: 'gesture-55', imagePath: '/images/emojis/Gesture/🫁 Lungs.png', name: '🫁 Lungs' },
      { id: 'gesture-56', imagePath: '/images/emojis/Gesture/🫂 People hugging.png', name: '🫂 People hugging' },
      { id: 'gesture-57', imagePath: '/images/emojis/Gesture/🫦 Biting lip.png', name: '🫦 Biting lip' },
      { id: 'gesture-58', imagePath: '/images/emojis/Gesture/🫰 Hand with index finger and thumb crossed.png', name: '🫰 Hand with index finger and thumb crossed' },
      { id: 'gesture-59', imagePath: '/images/emojis/Gesture/🫱 Rightwards hand.png', name: '🫱 Rightwards hand' },
      { id: 'gesture-60', imagePath: '/images/emojis/Gesture/🫲 Leftwards hand.png', name: '🫲 Leftwards hand' },
      { id: 'gesture-61', imagePath: '/images/emojis/Gesture/🫴 Palm-up hand.png', name: '🫴 Palm-up hand' },
      { id: 'gesture-62', imagePath: '/images/emojis/Gesture/🫵 Index pointing at the viewer.png', name: '🫵 Index pointing at the viewer' },
      { id: 'gesture-63', imagePath: '/images/emojis/Gesture/🫶 Heart hands.png', name: '🫶 Heart hands' },
      { id: 'gesture-64', imagePath: '/images/emojis/Gesture/🫷 Leftwards pushing hand.png', name: '🫷 Leftwards pushing hand' },
      { id: 'gesture-65', imagePath: '/images/emojis/Gesture/🫸 Rightwards pushing hand.png', name: '🫸 Rightwards pushing hand' },
    ],
  },
  {
    name: 'Symbols',
    items: [
      { id: 'symbols-1', imagePath: '/images/emojis/Symbols/‼️ Red double exclamation mark.png', name: '‼️ Red double exclamation mark' },
      { id: 'symbols-2', imagePath: '/images/emojis/Symbols/⁉️ Red exclamation mark and question mark.png', name: '⁉️ Red exclamation mark and question mark' },
      { id: 'symbols-3', imagePath: '/images/emojis/Symbols/Ⓜ️ Circled M.png', name: 'Ⓜ️ Circled M' },
      { id: 'symbols-4', imagePath: '/images/emojis/Symbols/☑️ Ballot box with tick.png', name: '☑️ Ballot box with tick' },
      { id: 'symbols-5', imagePath: '/images/emojis/Symbols/☢️ Radioactive.png', name: '☢️ Radioactive' },
      { id: 'symbols-6', imagePath: '/images/emojis/Symbols/☣️ Biohazard.png', name: '☣️ Biohazard' },
      { id: 'symbols-7', imagePath: '/images/emojis/Symbols/♠️ Spades suit.png', name: '♠️ Spades suit' },
      { id: 'symbols-8', imagePath: '/images/emojis/Symbols/♣️ Clubs suit.png', name: '♣️ Clubs suit' },
      { id: 'symbols-9', imagePath: '/images/emojis/Symbols/♥️ Hearts suit.png', name: '♥️ Hearts suit' },
      { id: 'symbols-10', imagePath: '/images/emojis/Symbols/♦️ Diamonds suit.png', name: '♦️ Diamonds suit' },
      { id: 'symbols-11', imagePath: '/images/emojis/Symbols/♨️ Hot springs.png', name: '♨️ Hot springs' },
      { id: 'symbols-12', imagePath: '/images/emojis/Symbols/♻️ Recycling symbol.png', name: '♻️ Recycling symbol' },
      { id: 'symbols-13', imagePath: '/images/emojis/Symbols/♿️ Wheelchair symbol.png', name: '♿️ Wheelchair symbol' },
      { id: 'symbols-14', imagePath: '/images/emojis/Symbols/⚜️ Fleur-de-lis.png', name: '⚜️ Fleur-de-lis' },
      { id: 'symbols-15', imagePath: '/images/emojis/Symbols/⚠️ Warning.png', name: '⚠️ Warning' },
      { id: 'symbols-16', imagePath: '/images/emojis/Symbols/⚪️ White circle.png', name: '⚪️ White circle' },
      { id: 'symbols-17', imagePath: '/images/emojis/Symbols/⚫️ Black circle.png', name: '⚫️ Black circle' },
      { id: 'symbols-18', imagePath: '/images/emojis/Symbols/⛔️ No entry.png', name: '⛔️ No entry' },
      { id: 'symbols-19', imagePath: '/images/emojis/Symbols/✅ Tick symbol.png', name: '✅ Tick symbol' },
      { id: 'symbols-20', imagePath: '/images/emojis/Symbols/✔️ Tick.png', name: '✔️ Tick' },
      { id: 'symbols-21', imagePath: '/images/emojis/Symbols/✳️ Eight spoked asterisk.png', name: '✳️ Eight spoked asterisk' },
      { id: 'symbols-22', imagePath: '/images/emojis/Symbols/✴️ Eight-pointed star.png', name: '✴️ Eight-pointed star' },
      { id: 'symbols-23', imagePath: '/images/emojis/Symbols/❇️ Sparkle.png', name: '❇️ Sparkle' },
      { id: 'symbols-24', imagePath: '/images/emojis/Symbols/❌ Cross mark.png', name: '❌ Cross mark' },
      { id: 'symbols-25', imagePath: '/images/emojis/Symbols/❎ X mark.png', name: '❎ X mark' },
      { id: 'symbols-26', imagePath: '/images/emojis/Symbols/❓ Red question mark.png', name: '❓ Red question mark' },
      { id: 'symbols-27', imagePath: '/images/emojis/Symbols/❔ White question mark.png', name: '❔ White question mark' },
      { id: 'symbols-28', imagePath: '/images/emojis/Symbols/❕ White exclamation mark.png', name: '❕ White exclamation mark' },
      { id: 'symbols-29', imagePath: '/images/emojis/Symbols/❗️ Red exclamation mark.png', name: '❗️ Red exclamation mark' },
      { id: 'symbols-30', imagePath: '/images/emojis/Symbols/❣️ Red heart as an exclamation mark.png', name: '❣️ Red heart as an exclamation mark' },
      { id: 'symbols-31', imagePath: '/images/emojis/Symbols/❤️ Red heart.png', name: '❤️ Red heart' },
      { id: 'symbols-32', imagePath: '/images/emojis/Symbols/❤️‍🔥 Heart on fire.png', name: '❤️‍🔥 Heart on fire' },
      { id: 'symbols-33', imagePath: '/images/emojis/Symbols/❤️‍🩹 Mending heart.png', name: '❤️‍🩹 Mending heart' },
      { id: 'symbols-34', imagePath: '/images/emojis/Symbols/➰ Curly loop.png', name: '➰ Curly loop' },
      { id: 'symbols-35', imagePath: '/images/emojis/Symbols/➿ Double curly loop.png', name: '➿ Double curly loop' },
      { id: 'symbols-36', imagePath: '/images/emojis/Symbols/⭕️ Circle mark.png', name: '⭕️ Circle mark' },
      { id: 'symbols-37', imagePath: '/images/emojis/Symbols/〰️ Wavy dash.png', name: '〰️ Wavy dash' },
      { id: 'symbols-38', imagePath: '/images/emojis/Symbols/〽️ Part alternation mark.png', name: '〽️ Part alternation mark' },
      { id: 'symbols-39', imagePath: '/images/emojis/Symbols/㊗️ Japanese sign meaning “congratulations”.png', name: '㊗️ Japanese sign meaning “congratulations”' },
      { id: 'symbols-40', imagePath: '/images/emojis/Symbols/㊙️ Japanese sign meaning “secret”.png', name: '㊙️ Japanese sign meaning “secret”' },
      { id: 'symbols-41', imagePath: '/images/emojis/Symbols/🀄️ Mahjong tile red dragon.png', name: '🀄️ Mahjong tile red dragon' },
      { id: 'symbols-42', imagePath: '/images/emojis/Symbols/🃏 Joker.png', name: '🃏 Joker' },
      { id: 'symbols-43', imagePath: '/images/emojis/Symbols/🅰️ Blood type A.png', name: '🅰️ Blood type A' },
      { id: 'symbols-44', imagePath: '/images/emojis/Symbols/🅱️ Blood type B.png', name: '🅱️ Blood type B' },
      { id: 'symbols-45', imagePath: '/images/emojis/Symbols/🅾️ Blood type O.png', name: '🅾️ Blood type O' },
      { id: 'symbols-46', imagePath: '/images/emojis/Symbols/🅿️ Parking sign.png', name: '🅿️ Parking sign' },
      { id: 'symbols-47', imagePath: '/images/emojis/Symbols/🆎 Blood type AB.png', name: '🆎 Blood type AB' },
      { id: 'symbols-48', imagePath: '/images/emojis/Symbols/🆑 CL sign.png', name: '🆑 CL sign' },
      { id: 'symbols-49', imagePath: '/images/emojis/Symbols/🆘 SOS sign.png', name: '🆘 SOS sign' },
      { id: 'symbols-50', imagePath: '/images/emojis/Symbols/🆚 Squared vs.png', name: '🆚 Squared vs' },
      { id: 'symbols-51', imagePath: '/images/emojis/Symbols/🈂️ Japanese sign meaning “service” or “service charge”.png', name: '🈂️ Japanese sign meaning “service” or “service charge”' },
      { id: 'symbols-52', imagePath: '/images/emojis/Symbols/🈚️ Japanese sign meaning “free of charge”.png', name: '🈚️ Japanese sign meaning “free of charge”' },
      { id: 'symbols-53', imagePath: '/images/emojis/Symbols/🈯️ Japanese sign meaning “reserved”.png', name: '🈯️ Japanese sign meaning “reserved”' },
      { id: 'symbols-54', imagePath: '/images/emojis/Symbols/🈲 Japanese sign meaning “prohibited”.png', name: '🈲 Japanese sign meaning “prohibited”' },
      { id: 'symbols-55', imagePath: '/images/emojis/Symbols/🈳 Japanese sign meaning “vacancy”.png', name: '🈳 Japanese sign meaning “vacancy”' },
      { id: 'symbols-56', imagePath: '/images/emojis/Symbols/🈴 Japanese sign meaning “passing (grade)”.png', name: '🈴 Japanese sign meaning “passing (grade)”' },
      { id: 'symbols-57', imagePath: '/images/emojis/Symbols/🈵 Japanese sign meaning “full; no vacancy”.png', name: '🈵 Japanese sign meaning “full; no vacancy”' },
      { id: 'symbols-58', imagePath: '/images/emojis/Symbols/🈶 Japanese sign meaning “not free of charge”.png', name: '🈶 Japanese sign meaning “not free of charge”' },
      { id: 'symbols-59', imagePath: '/images/emojis/Symbols/🈷️ Japanese sign meaning “monthly amount”.png', name: '🈷️ Japanese sign meaning “monthly amount”' },
      { id: 'symbols-60', imagePath: '/images/emojis/Symbols/🈸 Japanese sign meaning “application”.png', name: '🈸 Japanese sign meaning “application”' },
      { id: 'symbols-61', imagePath: '/images/emojis/Symbols/🈹 Japanese sign meaning “discount”.png', name: '🈹 Japanese sign meaning “discount”' },
      { id: 'symbols-62', imagePath: '/images/emojis/Symbols/🈺 Japanese sign meaning “open for business”.png', name: '🈺 Japanese sign meaning “open for business”' },
      { id: 'symbols-63', imagePath: '/images/emojis/Symbols/🉐 Japanese sign meaning “bargain”.png', name: '🉐 Japanese sign meaning “bargain”' },
      { id: 'symbols-64', imagePath: '/images/emojis/Symbols/🉑 Japanese sign meaning “acceptable”.png', name: '🉑 Japanese sign meaning “acceptable”' },
      { id: 'symbols-65', imagePath: '/images/emojis/Symbols/🌀 Cyclone.png', name: '🌀 Cyclone' },
      { id: 'symbols-66', imagePath: '/images/emojis/Symbols/🌐 Globe with meridians.png', name: '🌐 Globe with meridians' },
      { id: 'symbols-67', imagePath: '/images/emojis/Symbols/🎴 Flower playing cards.png', name: '🎴 Flower playing cards' },
      { id: 'symbols-68', imagePath: '/images/emojis/Symbols/🏧 ATM sign.png', name: '🏧 ATM sign' },
      { id: 'symbols-69', imagePath: '/images/emojis/Symbols/💓 Beating heart.png', name: '💓 Beating heart' },
      { id: 'symbols-70', imagePath: '/images/emojis/Symbols/💔 Broken heart.png', name: '💔 Broken heart' },
      { id: 'symbols-71', imagePath: '/images/emojis/Symbols/💕 Two hearts.png', name: '💕 Two hearts' },
      { id: 'symbols-72', imagePath: '/images/emojis/Symbols/💖 Sparkling heart.png', name: '💖 Sparkling heart' },
      { id: 'symbols-73', imagePath: '/images/emojis/Symbols/💗 Growing heart.png', name: '💗 Growing heart' },
      { id: 'symbols-74', imagePath: '/images/emojis/Symbols/💘 Heart with arrow.png', name: '💘 Heart with arrow' },
      { id: 'symbols-75', imagePath: '/images/emojis/Symbols/💙 Blue heart.png', name: '💙 Blue heart' },
      { id: 'symbols-76', imagePath: '/images/emojis/Symbols/💚 Green heart.png', name: '💚 Green heart' },
      { id: 'symbols-77', imagePath: '/images/emojis/Symbols/💛 Yellow heart.png', name: '💛 Yellow heart' },
      { id: 'symbols-78', imagePath: '/images/emojis/Symbols/💜 Purple heart.png', name: '💜 Purple heart' },
      { id: 'symbols-79', imagePath: '/images/emojis/Symbols/💝 Heart with ribbon.png', name: '💝 Heart with ribbon' },
      { id: 'symbols-80', imagePath: '/images/emojis/Symbols/💞 Revolving hearts.png', name: '💞 Revolving hearts' },
      { id: 'symbols-81', imagePath: '/images/emojis/Symbols/💠 Diamond shape with a dot inside.png', name: '💠 Diamond shape with a dot inside' },
      { id: 'symbols-82', imagePath: '/images/emojis/Symbols/💢 Anger symbol.png', name: '💢 Anger symbol' },
      { id: 'symbols-83', imagePath: '/images/emojis/Symbols/💤 Sleeping sign.png', name: '💤 Sleeping sign' },
      { id: 'symbols-84', imagePath: '/images/emojis/Symbols/💬 Speech balloon.png', name: '💬 Speech balloon' },
      { id: 'symbols-85', imagePath: '/images/emojis/Symbols/💭 Thought balloon.png', name: '💭 Thought balloon' },
      { id: 'symbols-86', imagePath: '/images/emojis/Symbols/💮 White flower.png', name: '💮 White flower' },
      { id: 'symbols-87', imagePath: '/images/emojis/Symbols/💯 Hundred points symbol.png', name: '💯 Hundred points symbol' },
      { id: 'symbols-88', imagePath: '/images/emojis/Symbols/💹 Chart with upwards trend and yen sign.png', name: '💹 Chart with upwards trend and yen sign' },
      { id: 'symbols-89', imagePath: '/images/emojis/Symbols/📛 Name badge.png', name: '📛 Name badge' },
      { id: 'symbols-90', imagePath: '/images/emojis/Symbols/📢 Public address loudspeaker.png', name: '📢 Public address loudspeaker' },
      { id: 'symbols-91', imagePath: '/images/emojis/Symbols/📣 Cheering megaphone.png', name: '📣 Cheering megaphone' },
      { id: 'symbols-92', imagePath: '/images/emojis/Symbols/📳 Vibration mode.png', name: '📳 Vibration mode' },
      { id: 'symbols-93', imagePath: '/images/emojis/Symbols/📴 Mobile phone off.png', name: '📴 Mobile phone off' },
      { id: 'symbols-94', imagePath: '/images/emojis/Symbols/📵 No mobile phones.png', name: '📵 No mobile phones' },
      { id: 'symbols-95', imagePath: '/images/emojis/Symbols/🔅 Low brightness symbol.png', name: '🔅 Low brightness symbol' },
      { id: 'symbols-96', imagePath: '/images/emojis/Symbols/🔆 High brightness symbol.png', name: '🔆 High brightness symbol' },
      { id: 'symbols-97', imagePath: '/images/emojis/Symbols/🔔 Bell.png', name: '🔔 Bell' },
      { id: 'symbols-98', imagePath: '/images/emojis/Symbols/🔕 Muted bell.png', name: '🔕 Muted bell' },
      { id: 'symbols-99', imagePath: '/images/emojis/Symbols/🔘 Radio button.png', name: '🔘 Radio button' },
      { id: 'symbols-100', imagePath: '/images/emojis/Symbols/🔞 No one under eighteen.png', name: '🔞 No one under eighteen' },
      { id: 'symbols-101', imagePath: '/images/emojis/Symbols/🔰 Japanese symbol for beginner.png', name: '🔰 Japanese symbol for beginner' },
      { id: 'symbols-102', imagePath: '/images/emojis/Symbols/🔱 Trident emblem.png', name: '🔱 Trident emblem' },
      { id: 'symbols-103', imagePath: '/images/emojis/Symbols/🔴 Red circle.png', name: '🔴 Red circle' },
      { id: 'symbols-104', imagePath: '/images/emojis/Symbols/🔵 Blue circle.png', name: '🔵 Blue circle' },
      { id: 'symbols-105', imagePath: '/images/emojis/Symbols/🔶 Large orange diamond.png', name: '🔶 Large orange diamond' },
      { id: 'symbols-106', imagePath: '/images/emojis/Symbols/🔷 Large blue diamond.png', name: '🔷 Large blue diamond' },
      { id: 'symbols-107', imagePath: '/images/emojis/Symbols/🔸 Small orange diamond.png', name: '🔸 Small orange diamond' },
      { id: 'symbols-108', imagePath: '/images/emojis/Symbols/🔹 Small blue diamond.png', name: '🔹 Small blue diamond' },
      { id: 'symbols-109', imagePath: '/images/emojis/Symbols/🔺 Red triangle pointed up.png', name: '🔺 Red triangle pointed up' },
      { id: 'symbols-110', imagePath: '/images/emojis/Symbols/🔻 Red triangle pointed down.png', name: '🔻 Red triangle pointed down' },
      { id: 'symbols-111', imagePath: '/images/emojis/Symbols/🖤 Black heart.png', name: '🖤 Black heart' },
      { id: 'symbols-112', imagePath: '/images/emojis/Symbols/🗯 Angry speech bubble.png', name: '🗯 Angry speech bubble' },
      { id: 'symbols-113', imagePath: '/images/emojis/Symbols/🚫 Prohibited.png', name: '🚫 Prohibited' },
      { id: 'symbols-114', imagePath: '/images/emojis/Symbols/🚭 No smoking sign.png', name: '🚭 No smoking sign' },
      { id: 'symbols-115', imagePath: '/images/emojis/Symbols/🚯 No littering.png', name: '🚯 No littering' },
      { id: 'symbols-116', imagePath: '/images/emojis/Symbols/🚱 Non-drinking water.png', name: '🚱 Non-drinking water' },
      { id: 'symbols-117', imagePath: '/images/emojis/Symbols/🚳 No bicycles.png', name: '🚳 No bicycles' },
      { id: 'symbols-118', imagePath: '/images/emojis/Symbols/🚷 No pedestrians.png', name: '🚷 No pedestrians' },
      { id: 'symbols-119', imagePath: '/images/emojis/Symbols/🚸 Children crossing.png', name: '🚸 Children crossing' },
      { id: 'symbols-120', imagePath: '/images/emojis/Symbols/🚹 Men’s symbol.png', name: '🚹 Men’s symbol' },
      { id: 'symbols-121', imagePath: '/images/emojis/Symbols/🚺 Women’s symbol.png', name: '🚺 Women’s symbol' },
      { id: 'symbols-122', imagePath: '/images/emojis/Symbols/🚼 Baby symbol.png', name: '🚼 Baby symbol' },
      { id: 'symbols-123', imagePath: '/images/emojis/Symbols/🚾 Toilet.png', name: '🚾 Toilet' },
      { id: 'symbols-124', imagePath: '/images/emojis/Symbols/🛂 Passport control.png', name: '🛂 Passport control' },
      { id: 'symbols-125', imagePath: '/images/emojis/Symbols/🛃 Customs.png', name: '🛃 Customs' },
      { id: 'symbols-126', imagePath: '/images/emojis/Symbols/🛄 Baggage claim.png', name: '🛄 Baggage claim' },
      { id: 'symbols-127', imagePath: '/images/emojis/Symbols/🛅 Left luggage.png', name: '🛅 Left luggage' },
      { id: 'symbols-128', imagePath: '/images/emojis/Symbols/🛑 Octogonal sign.png', name: '🛑 Octogonal sign' },
      { id: 'symbols-129', imagePath: '/images/emojis/Symbols/🛗 Lift.png', name: '🛗 Lift' },
      { id: 'symbols-130', imagePath: '/images/emojis/Symbols/🛜 Wireless.png', name: '🛜 Wireless' },
      { id: 'symbols-131', imagePath: '/images/emojis/Symbols/🟠 Orange circle.png', name: '🟠 Orange circle' },
      { id: 'symbols-132', imagePath: '/images/emojis/Symbols/🟡 Yellow circle.png', name: '🟡 Yellow circle' },
      { id: 'symbols-133', imagePath: '/images/emojis/Symbols/🟢 Green circle.png', name: '🟢 Green circle' },
      { id: 'symbols-134', imagePath: '/images/emojis/Symbols/🟣 Purple circle.png', name: '🟣 Purple circle' },
      { id: 'symbols-135', imagePath: '/images/emojis/Symbols/🟤 Brown circle.png', name: '🟤 Brown circle' },
      { id: 'symbols-136', imagePath: '/images/emojis/Symbols/🤍 White heart.png', name: '🤍 White heart' },
      { id: 'symbols-137', imagePath: '/images/emojis/Symbols/🤎 Brown heart.png', name: '🤎 Brown heart' },
      { id: 'symbols-138', imagePath: '/images/emojis/Symbols/🧡 Orange heart.png', name: '🧡 Orange heart' },
      { id: 'symbols-139', imagePath: '/images/emojis/Symbols/🩵 Light blue heart.png', name: '🩵 Light blue heart' },
      { id: 'symbols-140', imagePath: '/images/emojis/Symbols/🩶 Grey heart.png', name: '🩶 Grey heart' },
      { id: 'symbols-141', imagePath: '/images/emojis/Symbols/🩷 Pink heart.png', name: '🩷 Pink heart' },
    ],
  },
  {
    name: 'Animals&Nature',
    items: [
      { id: 'animals-1', imagePath: '/images/emojis/Animals&Nature/Black bird.png', name: 'Black bird' },
      { id: 'animals-2', imagePath: '/images/emojis/Animals&Nature/☀️ Sun.png', name: '☀️ Sun' },
      { id: 'animals-3', imagePath: '/images/emojis/Animals&Nature/☁️ Cloud.png', name: '☁️ Cloud' },
      { id: 'animals-4', imagePath: '/images/emojis/Animals&Nature/☂️ Umbrella.png', name: '☂️ Umbrella' },
      { id: 'animals-5', imagePath: '/images/emojis/Animals&Nature/☃️ Snowman with snowflakes.png', name: '☃️ Snowman with snowflakes' },
      { id: 'animals-6', imagePath: '/images/emojis/Animals&Nature/☄️ Comet.png', name: '☄️ Comet' },
      { id: 'animals-7', imagePath: '/images/emojis/Animals&Nature/☔️ Umbrella with rain drops.png', name: '☔️ Umbrella with rain drops' },
      { id: 'animals-8', imagePath: '/images/emojis/Animals&Nature/☘️ Shamrock.png', name: '☘️ Shamrock' },
      { id: 'animals-9', imagePath: '/images/emojis/Animals&Nature/⚡️ Lightning bolt.png', name: '⚡️ Lightning bolt' },
      { id: 'animals-10', imagePath: '/images/emojis/Animals&Nature/⛄️ Snowman.png', name: '⛄️ Snowman' },
      { id: 'animals-11', imagePath: '/images/emojis/Animals&Nature/⛅️ Sun behind cloud.png', name: '⛅️ Sun behind cloud' },
      { id: 'animals-12', imagePath: '/images/emojis/Animals&Nature/⛈ Cloud with lightning and rain.png', name: '⛈ Cloud with lightning and rain' },
      { id: 'animals-13', imagePath: '/images/emojis/Animals&Nature/✨ Sparkles.png', name: '✨ Sparkles' },
      { id: 'animals-14', imagePath: '/images/emojis/Animals&Nature/❄️ Snowflake.png', name: '❄️ Snowflake' },
      { id: 'animals-15', imagePath: '/images/emojis/Animals&Nature/⭐️ Star.png', name: '⭐️ Star' },
      { id: 'animals-16', imagePath: '/images/emojis/Animals&Nature/🌈 Rainbow.png', name: '🌈 Rainbow' },
      { id: 'animals-17', imagePath: '/images/emojis/Animals&Nature/🌊 Wave.png', name: '🌊 Wave' },
      { id: 'animals-18', imagePath: '/images/emojis/Animals&Nature/🌍 Globe showing Europe and Africa.png', name: '🌍 Globe showing Europe and Africa' },
      { id: 'animals-19', imagePath: '/images/emojis/Animals&Nature/🌎 Globe showing Americas.png', name: '🌎 Globe showing Americas' },
      { id: 'animals-20', imagePath: '/images/emojis/Animals&Nature/🌏 Globe showing Asia and Australia.png', name: '🌏 Globe showing Asia and Australia' },
      { id: 'animals-21', imagePath: '/images/emojis/Animals&Nature/🌑 New moon.png', name: '🌑 New moon' },
      { id: 'animals-22', imagePath: '/images/emojis/Animals&Nature/🌒 Waxing crescent moon.png', name: '🌒 Waxing crescent moon' },
      { id: 'animals-23', imagePath: '/images/emojis/Animals&Nature/🌓 First quarter moon.png', name: '🌓 First quarter moon' },
      { id: 'animals-24', imagePath: '/images/emojis/Animals&Nature/🌔 Waxing gibbous moon.png', name: '🌔 Waxing gibbous moon' },
      { id: 'animals-25', imagePath: '/images/emojis/Animals&Nature/🌕 Full moon.png', name: '🌕 Full moon' },
      { id: 'animals-26', imagePath: '/images/emojis/Animals&Nature/🌖 Waning gibbous moon.png', name: '🌖 Waning gibbous moon' },
      { id: 'animals-27', imagePath: '/images/emojis/Animals&Nature/🌗 Last quarter moon.png', name: '🌗 Last quarter moon' },
      { id: 'animals-28', imagePath: '/images/emojis/Animals&Nature/🌘 Waning crescent moon.png', name: '🌘 Waning crescent moon' },
      { id: 'animals-29', imagePath: '/images/emojis/Animals&Nature/🌙 Crescent moon.png', name: '🌙 Crescent moon' },
      { id: 'animals-30', imagePath: '/images/emojis/Animals&Nature/🌚 New moon with face.png', name: '🌚 New moon with face' },
      { id: 'animals-31', imagePath: '/images/emojis/Animals&Nature/🌛 First quarter moon with face.png', name: '🌛 First quarter moon with face' },
      { id: 'animals-32', imagePath: '/images/emojis/Animals&Nature/🌜 Last quarter moon with face.png', name: '🌜 Last quarter moon with face' },
      { id: 'animals-33', imagePath: '/images/emojis/Animals&Nature/🌝 Full moon with face.png', name: '🌝 Full moon with face' },
      { id: 'animals-34', imagePath: '/images/emojis/Animals&Nature/🌞 Sun with face.png', name: '🌞 Sun with face' },
      { id: 'animals-35', imagePath: '/images/emojis/Animals&Nature/🌟 Glowing star.png', name: '🌟 Glowing star' },
      { id: 'animals-36', imagePath: '/images/emojis/Animals&Nature/🌤 Sun behind small cloud.png', name: '🌤 Sun behind small cloud' },
      { id: 'animals-37', imagePath: '/images/emojis/Animals&Nature/🌥 Sun behind large cloud.png', name: '🌥 Sun behind large cloud' },
      { id: 'animals-38', imagePath: '/images/emojis/Animals&Nature/🌦 Sun behind rain cloud.png', name: '🌦 Sun behind rain cloud' },
      { id: 'animals-39', imagePath: '/images/emojis/Animals&Nature/🌧 Cloud with rain.png', name: '🌧 Cloud with rain' },
      { id: 'animals-40', imagePath: '/images/emojis/Animals&Nature/🌨 Cloud with snow.png', name: '🌨 Cloud with snow' },
      { id: 'animals-41', imagePath: '/images/emojis/Animals&Nature/🌩 Cloud with lightning.png', name: '🌩 Cloud with lightning' },
      { id: 'animals-42', imagePath: '/images/emojis/Animals&Nature/🌪 Tornado.png', name: '🌪 Tornado' },
      { id: 'animals-43', imagePath: '/images/emojis/Animals&Nature/🌫 Fog.png', name: '🌫 Fog' },
      { id: 'animals-44', imagePath: '/images/emojis/Animals&Nature/🌬 Wind blowing face.png', name: '🌬 Wind blowing face' },
      { id: 'animals-45', imagePath: '/images/emojis/Animals&Nature/🌱 Seedling.png', name: '🌱 Seedling' },
      { id: 'animals-46', imagePath: '/images/emojis/Animals&Nature/🌲 Evergreen tree.png', name: '🌲 Evergreen tree' },
      { id: 'animals-47', imagePath: '/images/emojis/Animals&Nature/🌳 Tree.png', name: '🌳 Tree' },
      { id: 'animals-48', imagePath: '/images/emojis/Animals&Nature/🌴 Palm tree.png', name: '🌴 Palm tree' },
      { id: 'animals-49', imagePath: '/images/emojis/Animals&Nature/🌵 Cactus.png', name: '🌵 Cactus' },
      { id: 'animals-50', imagePath: '/images/emojis/Animals&Nature/🌷 Tulip.png', name: '🌷 Tulip' },
      { id: 'animals-51', imagePath: '/images/emojis/Animals&Nature/🌸 Cherry blossom.png', name: '🌸 Cherry blossom' },
      { id: 'animals-52', imagePath: '/images/emojis/Animals&Nature/🌹 Rose.png', name: '🌹 Rose' },
      { id: 'animals-53', imagePath: '/images/emojis/Animals&Nature/🌺 Hibiscus.png', name: '🌺 Hibiscus' },
      { id: 'animals-54', imagePath: '/images/emojis/Animals&Nature/🌻 Sunflower.png', name: '🌻 Sunflower' },
      { id: 'animals-55', imagePath: '/images/emojis/Animals&Nature/🌼 Flower.png', name: '🌼 Flower' },
      { id: 'animals-56', imagePath: '/images/emojis/Animals&Nature/🌾 Ear of rice.png', name: '🌾 Ear of rice' },
      { id: 'animals-57', imagePath: '/images/emojis/Animals&Nature/🌿 Herb.png', name: '🌿 Herb' },
      { id: 'animals-58', imagePath: '/images/emojis/Animals&Nature/🍀 Four-leaf clover.png', name: '🍀 Four-leaf clover' },
      { id: 'animals-59', imagePath: '/images/emojis/Animals&Nature/🍁 Maple leaf.png', name: '🍁 Maple leaf' },
      { id: 'animals-60', imagePath: '/images/emojis/Animals&Nature/🍂 Fallen leaves.png', name: '🍂 Fallen leaves' },
      { id: 'animals-61', imagePath: '/images/emojis/Animals&Nature/🍃 Leaves fluttering in wind.png', name: '🍃 Leaves fluttering in wind' },
      { id: 'animals-62', imagePath: '/images/emojis/Animals&Nature/🍄 Mushroom.png', name: '🍄 Mushroom' },
      { id: 'animals-63', imagePath: '/images/emojis/Animals&Nature/🍄‍🟫 Brown mushroom.png', name: '🍄‍🟫 Brown mushroom' },
      { id: 'animals-64', imagePath: '/images/emojis/Animals&Nature/🎄 Christmas tree.png', name: '🎄 Christmas tree' },
      { id: 'animals-65', imagePath: '/images/emojis/Animals&Nature/🎋 Tanabata.png', name: '🎋 Tanabata' },
      { id: 'animals-66', imagePath: '/images/emojis/Animals&Nature/🎍 Pine decoration.png', name: '🎍 Pine decoration' },
      { id: 'animals-67', imagePath: '/images/emojis/Animals&Nature/🐀 Rat.png', name: '🐀 Rat' },
      { id: 'animals-68', imagePath: '/images/emojis/Animals&Nature/🐁 Mouse.png', name: '🐁 Mouse' },
      { id: 'animals-69', imagePath: '/images/emojis/Animals&Nature/🐂 Ox.png', name: '🐂 Ox' },
      { id: 'animals-70', imagePath: '/images/emojis/Animals&Nature/🐃 Water Buffalo.png', name: '🐃 Water Buffalo' },
      { id: 'animals-71', imagePath: '/images/emojis/Animals&Nature/🐄 Cow.png', name: '🐄 Cow' },
      { id: 'animals-72', imagePath: '/images/emojis/Animals&Nature/🐅 Tiger.png', name: '🐅 Tiger' },
      { id: 'animals-73', imagePath: '/images/emojis/Animals&Nature/🐆 Leopard.png', name: '🐆 Leopard' },
      { id: 'animals-74', imagePath: '/images/emojis/Animals&Nature/🐇 Rabbit.png', name: '🐇 Rabbit' },
      { id: 'animals-75', imagePath: '/images/emojis/Animals&Nature/🐈 Cat.png', name: '🐈 Cat' },
      { id: 'animals-76', imagePath: '/images/emojis/Animals&Nature/🐈‍⬛ Black cat.png', name: '🐈‍⬛ Black cat' },
      { id: 'animals-77', imagePath: '/images/emojis/Animals&Nature/🐉 Dragon.png', name: '🐉 Dragon' },
      { id: 'animals-78', imagePath: '/images/emojis/Animals&Nature/🐊 Crocodile.png', name: '🐊 Crocodile' },
      { id: 'animals-79', imagePath: '/images/emojis/Animals&Nature/🐋 Whale.png', name: '🐋 Whale' },
      { id: 'animals-80', imagePath: '/images/emojis/Animals&Nature/🐌 Snail.png', name: '🐌 Snail' },
      { id: 'animals-81', imagePath: '/images/emojis/Animals&Nature/🐍 Snake.png', name: '🐍 Snake' },
      { id: 'animals-82', imagePath: '/images/emojis/Animals&Nature/🐎 Horse.png', name: '🐎 Horse' },
      { id: 'animals-83', imagePath: '/images/emojis/Animals&Nature/🐏 Ram.png', name: '🐏 Ram' },
      { id: 'animals-84', imagePath: '/images/emojis/Animals&Nature/🐐 Goat.png', name: '🐐 Goat' },
      { id: 'animals-85', imagePath: '/images/emojis/Animals&Nature/🐑 Sheep.png', name: '🐑 Sheep' },
      { id: 'animals-86', imagePath: '/images/emojis/Animals&Nature/🐒 Monkey.png', name: '🐒 Monkey' },
      { id: 'animals-87', imagePath: '/images/emojis/Animals&Nature/🐓 Cockerel.png', name: '🐓 Cockerel' },
      { id: 'animals-88', imagePath: '/images/emojis/Animals&Nature/🐔 Chicken.png', name: '🐔 Chicken' },
      { id: 'animals-89', imagePath: '/images/emojis/Animals&Nature/🐕 Dog.png', name: '🐕 Dog' },
      { id: 'animals-90', imagePath: '/images/emojis/Animals&Nature/🐕‍🦺 Service dog.png', name: '🐕‍🦺 Service dog' },
      { id: 'animals-91', imagePath: '/images/emojis/Animals&Nature/🐖 Pig.png', name: '🐖 Pig' },
      { id: 'animals-92', imagePath: '/images/emojis/Animals&Nature/🐗 Boar.png', name: '🐗 Boar' },
      { id: 'animals-93', imagePath: '/images/emojis/Animals&Nature/🐘 Elephant.png', name: '🐘 Elephant' },
      { id: 'animals-94', imagePath: '/images/emojis/Animals&Nature/🐙 Octopus.png', name: '🐙 Octopus' },
      { id: 'animals-95', imagePath: '/images/emojis/Animals&Nature/🐚 Seashell.png', name: '🐚 Seashell' },
      { id: 'animals-96', imagePath: '/images/emojis/Animals&Nature/🐛 Bug.png', name: '🐛 Bug' },
      { id: 'animals-97', imagePath: '/images/emojis/Animals&Nature/🐜 Ant.png', name: '🐜 Ant' },
      { id: 'animals-98', imagePath: '/images/emojis/Animals&Nature/🐝 Bee.png', name: '🐝 Bee' },
      { id: 'animals-99', imagePath: '/images/emojis/Animals&Nature/🐞 Ladybird.png', name: '🐞 Ladybird' },
      { id: 'animals-100', imagePath: '/images/emojis/Animals&Nature/🐟 Fish.png', name: '🐟 Fish' },
      { id: 'animals-101', imagePath: '/images/emojis/Animals&Nature/🐠 Tropical fish.png', name: '🐠 Tropical fish' },
      { id: 'animals-102', imagePath: '/images/emojis/Animals&Nature/🐡 Blowfish.png', name: '🐡 Blowfish' },
      { id: 'animals-103', imagePath: '/images/emojis/Animals&Nature/🐢 Turtle.png', name: '🐢 Turtle' },
      { id: 'animals-104', imagePath: '/images/emojis/Animals&Nature/🐣 Hatching chick.png', name: '🐣 Hatching chick' },
      { id: 'animals-105', imagePath: '/images/emojis/Animals&Nature/🐤 Baby chick.png', name: '🐤 Baby chick' },
      { id: 'animals-106', imagePath: '/images/emojis/Animals&Nature/🐥 Standing chick.png', name: '🐥 Standing chick' },
      { id: 'animals-107', imagePath: '/images/emojis/Animals&Nature/🐦 Bird.png', name: '🐦 Bird' },
      { id: 'animals-108', imagePath: '/images/emojis/Animals&Nature/🐦‍🔥 Phoenix.png', name: '🐦‍🔥 Phoenix' },
      { id: 'animals-109', imagePath: '/images/emojis/Animals&Nature/🐧 Penguin.png', name: '🐧 Penguin' },
      { id: 'animals-110', imagePath: '/images/emojis/Animals&Nature/🐨 Koala face.png', name: '🐨 Koala face' },
      { id: 'animals-111', imagePath: '/images/emojis/Animals&Nature/🐩 Poodle.png', name: '🐩 Poodle' },
      { id: 'animals-112', imagePath: '/images/emojis/Animals&Nature/🐪 Camel.png', name: '🐪 Camel' },
      { id: 'animals-113', imagePath: '/images/emojis/Animals&Nature/🐫 Two-hump camel.png', name: '🐫 Two-hump camel' },
      { id: 'animals-114', imagePath: '/images/emojis/Animals&Nature/🐬 Dolphin.png', name: '🐬 Dolphin' },
      { id: 'animals-115', imagePath: '/images/emojis/Animals&Nature/🐭 Mouse face.png', name: '🐭 Mouse face' },
      { id: 'animals-116', imagePath: '/images/emojis/Animals&Nature/🐮 Cow face.png', name: '🐮 Cow face' },
      { id: 'animals-117', imagePath: '/images/emojis/Animals&Nature/🐯 Tiger face.png', name: '🐯 Tiger face' },
      { id: 'animals-118', imagePath: '/images/emojis/Animals&Nature/🐰 Rabbit face.png', name: '🐰 Rabbit face' },
      { id: 'animals-119', imagePath: '/images/emojis/Animals&Nature/🐱 Cat face.png', name: '🐱 Cat face' },
      { id: 'animals-120', imagePath: '/images/emojis/Animals&Nature/🐲 Dragon head.png', name: '🐲 Dragon head' },
      { id: 'animals-121', imagePath: '/images/emojis/Animals&Nature/🐳 Spouting whale.png', name: '🐳 Spouting whale' },
      { id: 'animals-122', imagePath: '/images/emojis/Animals&Nature/🐴 Horse head.png', name: '🐴 Horse head' },
      { id: 'animals-123', imagePath: '/images/emojis/Animals&Nature/🐵 Monkey face.png', name: '🐵 Monkey face' },
      { id: 'animals-124', imagePath: '/images/emojis/Animals&Nature/🐶 Dog face.png', name: '🐶 Dog face' },
      { id: 'animals-125', imagePath: '/images/emojis/Animals&Nature/🐷 Pig face.png', name: '🐷 Pig face' },
      { id: 'animals-126', imagePath: '/images/emojis/Animals&Nature/🐸 Frog face.png', name: '🐸 Frog face' },
      { id: 'animals-127', imagePath: '/images/emojis/Animals&Nature/🐹 Hamster face.png', name: '🐹 Hamster face' },
      { id: 'animals-128', imagePath: '/images/emojis/Animals&Nature/🐺 Wolf.png', name: '🐺 Wolf' },
      { id: 'animals-129', imagePath: '/images/emojis/Animals&Nature/🐻 Panda face.png', name: '🐻 Panda face' },
      { id: 'animals-130', imagePath: '/images/emojis/Animals&Nature/🐻‍❄️ Polar face.png', name: '🐻‍❄️ Polar face' },
      { id: 'animals-131', imagePath: '/images/emojis/Animals&Nature/🐼 Bear face.png', name: '🐼 Bear face' },
      { id: 'animals-132', imagePath: '/images/emojis/Animals&Nature/🐽 Pig nose.png', name: '🐽 Pig nose' },
      { id: 'animals-133', imagePath: '/images/emojis/Animals&Nature/🐾 Paw prints.png', name: '🐾 Paw prints' },
      { id: 'animals-134', imagePath: '/images/emojis/Animals&Nature/🐿 Chipmunk.png', name: '🐿 Chipmunk' },
      { id: 'animals-135', imagePath: '/images/emojis/Animals&Nature/💐 Bouquet.png', name: '💐 Bouquet' },
      { id: 'animals-136', imagePath: '/images/emojis/Animals&Nature/💥 Explosion.png', name: '💥 Explosion' },
      { id: 'animals-137', imagePath: '/images/emojis/Animals&Nature/💦 Water droplets.png', name: '💦 Water droplets' },
      { id: 'animals-138', imagePath: '/images/emojis/Animals&Nature/💧 Droplet.png', name: '💧 Droplet' },
      { id: 'animals-139', imagePath: '/images/emojis/Animals&Nature/💨 Gust of wind.png', name: '💨 Gust of wind' },
      { id: 'animals-140', imagePath: '/images/emojis/Animals&Nature/💫 Dizzy symbol.png', name: '💫 Dizzy symbol' },
      { id: 'animals-141', imagePath: '/images/emojis/Animals&Nature/🔥 Fire.png', name: '🔥 Fire' },
      { id: 'animals-142', imagePath: '/images/emojis/Animals&Nature/🕊 Dove.png', name: '🕊 Dove' },
      { id: 'animals-143', imagePath: '/images/emojis/Animals&Nature/🕷 Spider.png', name: '🕷 Spider' },
      { id: 'animals-144', imagePath: '/images/emojis/Animals&Nature/🕸 Spiderweb.png', name: '🕸 Spiderweb' },
      { id: 'animals-145', imagePath: '/images/emojis/Animals&Nature/🙈 See-no-evil monkey face.png', name: '🙈 See-no-evil monkey face' },
      { id: 'animals-146', imagePath: '/images/emojis/Animals&Nature/🙉 Hear-no-evil monkey face.png', name: '🙉 Hear-no-evil monkey face' },
      { id: 'animals-147', imagePath: '/images/emojis/Animals&Nature/🙊 Speak-no-evil monkey face.png', name: '🙊 Speak-no-evil monkey face' },
      { id: 'animals-148', imagePath: '/images/emojis/Animals&Nature/🥀 Wilted rose.png', name: '🥀 Wilted rose' },
      { id: 'animals-149', imagePath: '/images/emojis/Animals&Nature/🦀 Crab.png', name: '🦀 Crab' },
      { id: 'animals-150', imagePath: '/images/emojis/Animals&Nature/🦁 Lion face.png', name: '🦁 Lion face' },
      { id: 'animals-151', imagePath: '/images/emojis/Animals&Nature/🦂 Scorpion.png', name: '🦂 Scorpion' },
      { id: 'animals-152', imagePath: '/images/emojis/Animals&Nature/🦃 Turkey.png', name: '🦃 Turkey' },
      { id: 'animals-153', imagePath: '/images/emojis/Animals&Nature/🦄 Unicorn.png', name: '🦄 Unicorn' },
      { id: 'animals-154', imagePath: '/images/emojis/Animals&Nature/🦅 Eagle.png', name: '🦅 Eagle' },
      { id: 'animals-155', imagePath: '/images/emojis/Animals&Nature/🦆 Duck.png', name: '🦆 Duck' },
      { id: 'animals-156', imagePath: '/images/emojis/Animals&Nature/🦇 Bat.png', name: '🦇 Bat' },
      { id: 'animals-157', imagePath: '/images/emojis/Animals&Nature/🦈 Shark.png', name: '🦈 Shark' },
      { id: 'animals-158', imagePath: '/images/emojis/Animals&Nature/🦉 Owl.png', name: '🦉 Owl' },
      { id: 'animals-159', imagePath: '/images/emojis/Animals&Nature/🦊 Fox face.png', name: '🦊 Fox face' },
      { id: 'animals-160', imagePath: '/images/emojis/Animals&Nature/🦋 Butterfly.png', name: '🦋 Butterfly' },
      { id: 'animals-161', imagePath: '/images/emojis/Animals&Nature/🦌 Deer.png', name: '🦌 Deer' },
      { id: 'animals-162', imagePath: '/images/emojis/Animals&Nature/🦍 Gorilla.png', name: '🦍 Gorilla' },
      { id: 'animals-163', imagePath: '/images/emojis/Animals&Nature/🦎 Lizard.png', name: '🦎 Lizard' },
      { id: 'animals-164', imagePath: '/images/emojis/Animals&Nature/🦏 Rhinoceros.png', name: '🦏 Rhinoceros' },
      { id: 'animals-165', imagePath: '/images/emojis/Animals&Nature/🦐 Shrimp.png', name: '🦐 Shrimp' },
      { id: 'animals-166', imagePath: '/images/emojis/Animals&Nature/🦑 Squid.png', name: '🦑 Squid' },
      { id: 'animals-167', imagePath: '/images/emojis/Animals&Nature/🦒 Giraffe.png', name: '🦒 Giraffe' },
      { id: 'animals-168', imagePath: '/images/emojis/Animals&Nature/🦓 Zebra.png', name: '🦓 Zebra' },
      { id: 'animals-169', imagePath: '/images/emojis/Animals&Nature/🦔 Hedgehog.png', name: '🦔 Hedgehog' },
      { id: 'animals-170', imagePath: '/images/emojis/Animals&Nature/🦕 Dinosaur.png', name: '🦕 Dinosaur' },
      { id: 'animals-171', imagePath: '/images/emojis/Animals&Nature/🦖 T-Rex.png', name: '🦖 T-Rex' },
      { id: 'animals-172', imagePath: '/images/emojis/Animals&Nature/🦗 Cricket.png', name: '🦗 Cricket' },
      { id: 'animals-173', imagePath: '/images/emojis/Animals&Nature/🦘 Kangaroo.png', name: '🦘 Kangaroo' },
      { id: 'animals-174', imagePath: '/images/emojis/Animals&Nature/🦙 Llama.png', name: '🦙 Llama' },
      { id: 'animals-175', imagePath: '/images/emojis/Animals&Nature/🦚 Peacock.png', name: '🦚 Peacock' },
      { id: 'animals-176', imagePath: '/images/emojis/Animals&Nature/🦛 Hippopotamus.png', name: '🦛 Hippopotamus' },
      { id: 'animals-177', imagePath: '/images/emojis/Animals&Nature/🦜 Parrot.png', name: '🦜 Parrot' },
      { id: 'animals-178', imagePath: '/images/emojis/Animals&Nature/🦝 Raccoon.png', name: '🦝 Raccoon' },
      { id: 'animals-179', imagePath: '/images/emojis/Animals&Nature/🦞 Lobster.png', name: '🦞 Lobster' },
      { id: 'animals-180', imagePath: '/images/emojis/Animals&Nature/🦟 Mosquito.png', name: '🦟 Mosquito' },
      { id: 'animals-181', imagePath: '/images/emojis/Animals&Nature/🦡 Badger.png', name: '🦡 Badger' },
      { id: 'animals-182', imagePath: '/images/emojis/Animals&Nature/🦢 Swan.png', name: '🦢 Swan' },
      { id: 'animals-183', imagePath: '/images/emojis/Animals&Nature/🦣 Mammoth.png', name: '🦣 Mammoth' },
      { id: 'animals-184', imagePath: '/images/emojis/Animals&Nature/🦤 Dodo bird.png', name: '🦤 Dodo bird' },
      { id: 'animals-185', imagePath: '/images/emojis/Animals&Nature/🦥 Sloth.png', name: '🦥 Sloth' },
      { id: 'animals-186', imagePath: '/images/emojis/Animals&Nature/🦦 Otter.png', name: '🦦 Otter' },
      { id: 'animals-187', imagePath: '/images/emojis/Animals&Nature/🦧 Orangutan.png', name: '🦧 Orangutan' },
      { id: 'animals-188', imagePath: '/images/emojis/Animals&Nature/🦨 Shunk.png', name: '🦨 Shunk' },
      { id: 'animals-189', imagePath: '/images/emojis/Animals&Nature/🦩 Flamingo.png', name: '🦩 Flamingo' },
      { id: 'animals-190', imagePath: '/images/emojis/Animals&Nature/🦫 Beaver.png', name: '🦫 Beaver' },
      { id: 'animals-191', imagePath: '/images/emojis/Animals&Nature/🦬 Bison.png', name: '🦬 Bison' },
      { id: 'animals-192', imagePath: '/images/emojis/Animals&Nature/🦭 Seal.png', name: '🦭 Seal' },
      { id: 'animals-193', imagePath: '/images/emojis/Animals&Nature/🦮 Guide dog.png', name: '🦮 Guide dog' },
      { id: 'animals-194', imagePath: '/images/emojis/Animals&Nature/🪐 Planet.png', name: '🪐 Planet' },
      { id: 'animals-195', imagePath: '/images/emojis/Animals&Nature/🪨 Rock.png', name: '🪨 Rock' },
      { id: 'animals-196', imagePath: '/images/emojis/Animals&Nature/🪰 Fly.png', name: '🪰 Fly' },
      { id: 'animals-197', imagePath: '/images/emojis/Animals&Nature/🪱 Worm.png', name: '🪱 Worm' },
      { id: 'animals-198', imagePath: '/images/emojis/Animals&Nature/🪲 Beetle.png', name: '🪲 Beetle' },
      { id: 'animals-199', imagePath: '/images/emojis/Animals&Nature/🪳 Coakroach.png', name: '🪳 Coakroach' },
      { id: 'animals-200', imagePath: '/images/emojis/Animals&Nature/🪴 Potted plant.png', name: '🪴 Potted plant' },
      { id: 'animals-201', imagePath: '/images/emojis/Animals&Nature/🪵 Wood.png', name: '🪵 Wood' },
      { id: 'animals-202', imagePath: '/images/emojis/Animals&Nature/🪶 Feather.png', name: '🪶 Feather' },
      { id: 'animals-203', imagePath: '/images/emojis/Animals&Nature/🪷 Lotus.png', name: '🪷 Lotus' },
      { id: 'animals-204', imagePath: '/images/emojis/Animals&Nature/🪸 Coral.png', name: '🪸 Coral' },
      { id: 'animals-205', imagePath: '/images/emojis/Animals&Nature/🪹 Empty nest.png', name: '🪹 Empty nest' },
      { id: 'animals-206', imagePath: '/images/emojis/Animals&Nature/🪺 Nest with eggs.png', name: '🪺 Nest with eggs' },
      { id: 'animals-207', imagePath: '/images/emojis/Animals&Nature/🪻 Hyacinth.png', name: '🪻 Hyacinth' },
      { id: 'animals-208', imagePath: '/images/emojis/Animals&Nature/🪼 Jellyfish.png', name: '🪼 Jellyfish' },
      { id: 'animals-209', imagePath: '/images/emojis/Animals&Nature/🪽 Wing.png', name: '🪽 Wing' },
      { id: 'animals-210', imagePath: '/images/emojis/Animals&Nature/🪿 Goose.png', name: '🪿 Goose' },
      { id: 'animals-211', imagePath: '/images/emojis/Animals&Nature/🫎 Moose.png', name: '🫎 Moose' },
      { id: 'animals-212', imagePath: '/images/emojis/Animals&Nature/🫏 Donkey.png', name: '🫏 Donkey' },
      { id: 'animals-213', imagePath: '/images/emojis/Animals&Nature/🫧 Bubbles.png', name: '🫧 Bubbles' },
    ],
  },
];
