// 表情分类配置
// 支持直接指定图片路径，图片应放在 public/images/emojis/ 目录下

export interface EmojiItem {
  id: string; // 唯一标识
  imagePath: string; // 图片路径，相对于 public 目录，例如: /images/emojis/smiley_1.png
  name?: string; // 可选：表情名称，用于alt文本
}

export interface EmojiCategory {
  name: string; // 分类名称，如 "Smileys", "People"
  items: EmojiItem[]; // 该分类下的表情列表
}

// 表情分类配置
// 你可以根据需要修改这个配置，添加图片路径
export const EMOJI_CATEGORIES: EmojiCategory[] = [
  {
    name: 'Smileys',
    items: [
      { id: 'smiley-1', imagePath: '/images/emojis/Smileys/Exhaling face.png', name: 'Exhaling face' },
      { id: 'smiley-2', imagePath: '/images/emojis/Smileys/Face in clouds.png', name: 'Face in clouds' },
      { id: 'smiley-3', imagePath: '/images/emojis/Smileys/Face with spiral eyes.png', name: 'Face with spiral eyes' },
      { id: 'smiley-4', imagePath: '/images/emojis/Smileys/Frowning face.png', name: 'Frowning face' },
      { id: 'smiley-5', imagePath: '/images/emojis/Smileys/Skull and crossbones.png', name: 'Skull and crossbones' },
      { id: 'smiley-6', imagePath: '/images/emojis/Smileys/Smiling face with glasses.png', name: 'Smiling face with glasses' },
      { id: 'smiley-7', imagePath: '/images/emojis/Smileys/Smiling face.png', name: 'Smiling face' },
      { id: 'smiley-8', imagePath: '/images/emojis/Smileys/Sneezing face.png', name: 'Sneezing face' },
      { id: 'smiley-9', imagePath: '/images/emojis/Smileys/🎃 Jack-o-lantern.png', name: '🎃 Jack-o-lantern' },
      { id: 'smiley-10', imagePath: '/images/emojis/Smileys/👹 Ogre.png', name: '👹 Ogre' },
      { id: 'smiley-11', imagePath: '/images/emojis/Smileys/👺 Goblin.png', name: '👺 Goblin' },
      { id: 'smiley-12', imagePath: '/images/emojis/Smileys/👻 Ghost.png', name: '👻 Ghost' },
      { id: 'smiley-13', imagePath: '/images/emojis/Smileys/👽 Alien.png', name: '👽 Alien' },
      { id: 'smiley-14', imagePath: '/images/emojis/Smileys/👾 Alien monster.png', name: '👾 Alien monster' },
      { id: 'smiley-15', imagePath: '/images/emojis/Smileys/👿 Angry face with horns.png', name: '👿 Angry face with horns' },
      { id: 'smiley-16', imagePath: '/images/emojis/Smileys/💀 Skull.png', name: '💀 Skull' },
      { id: 'smiley-17', imagePath: '/images/emojis/Smileys/💩 Pile of poop.png', name: '💩 Pile of poop' },
      { id: 'smiley-18', imagePath: '/images/emojis/Smileys/😀 Grinning face.png', name: '😀 Grinning face' },
      { id: 'smiley-19', imagePath: '/images/emojis/Smileys/😁 Beaming face with smiling eyes.png', name: '😁 Beaming face with smiling eyes' },
      { id: 'smiley-20', imagePath: '/images/emojis/Smileys/😂 Face with tears of joy.png', name: '😂 Face with tears of joy' },
      { id: 'smiley-21', imagePath: '/images/emojis/Smileys/😃 Grinning face with big eyes.png', name: '😃 Grinning face with big eyes' },
      { id: 'smiley-22', imagePath: '/images/emojis/Smileys/😄 Grinning face with smiling eyes.png', name: '😄 Grinning face with smiling eyes' },
      { id: 'smiley-23', imagePath: '/images/emojis/Smileys/😅 Grinning face with sweat.png', name: '😅 Grinning face with sweat' },
      { id: 'smiley-24', imagePath: '/images/emojis/Smileys/😆 Grinning face with squinting eyes.png', name: '😆 Grinning face with squinting eyes' },
      { id: 'smiley-25', imagePath: '/images/emojis/Smileys/😇 Smiling face with halo.png', name: '😇 Smiling face with halo' },
      { id: 'smiley-26', imagePath: '/images/emojis/Smileys/😈 Smiling face with horns.png', name: '😈 Smiling face with horns' },
      { id: 'smiley-27', imagePath: '/images/emojis/Smileys/😉 Winking face.png', name: '😉 Winking face' },
      { id: 'smiley-28', imagePath: '/images/emojis/Smileys/😊 Smiling face with smiling eyes.png', name: '😊 Smiling face with smiling eyes' },
      { id: 'smiley-29', imagePath: '/images/emojis/Smileys/😋 Smiling face licking lips.png', name: '😋 Smiling face licking lips' },
      { id: 'smiley-30', imagePath: '/images/emojis/Smileys/😌 Relieved face.png', name: '😌 Relieved face' },
      { id: 'smiley-31', imagePath: '/images/emojis/Smileys/😍 Smiling face with heart-eyes.png', name: '😍 Smiling face with heart-eyes' },
      { id: 'smiley-32', imagePath: '/images/emojis/Smileys/😎 Smiling face with sunglasses.png', name: '😎 Smiling face with sunglasses' },
      { id: 'smiley-33', imagePath: '/images/emojis/Smileys/😏 Smirking face.png', name: '😏 Smirking face' },
      { id: 'smiley-34', imagePath: '/images/emojis/Smileys/😐 Neutral face.png', name: '😐 Neutral face' },
      { id: 'smiley-35', imagePath: '/images/emojis/Smileys/😑 Expressionless face.png', name: '😑 Expressionless face' },
      { id: 'smiley-36', imagePath: '/images/emojis/Smileys/😒 Unamused face.png', name: '😒 Unamused face' },
      { id: 'smiley-37', imagePath: '/images/emojis/Smileys/😓 Downcast face with sweat.png', name: '😓 Downcast face with sweat' },
      { id: 'smiley-38', imagePath: '/images/emojis/Smileys/😔 Sad pensive face.png', name: '😔 Sad pensive face' },
      { id: 'smiley-39', imagePath: '/images/emojis/Smileys/😕 Confused face.png', name: '😕 Confused face' },
      { id: 'smiley-40', imagePath: '/images/emojis/Smileys/😖 Confounded face.png', name: '😖 Confounded face' },
      { id: 'smiley-41', imagePath: '/images/emojis/Smileys/😗 Kissing face.png', name: '😗 Kissing face' },
      { id: 'smiley-42', imagePath: '/images/emojis/Smileys/😘 Face blowing a kiss.png', name: '😘 Face blowing a kiss' },
      { id: 'smiley-43', imagePath: '/images/emojis/Smileys/😙 Kissing face with smiling eyes.png', name: '😙 Kissing face with smiling eyes' },
      { id: 'smiley-44', imagePath: '/images/emojis/Smileys/😚 Kissing face with closed eyes.png', name: '😚 Kissing face with closed eyes' },
      { id: 'smiley-45', imagePath: '/images/emojis/Smileys/😛 Face with stuck-out tongue.png', name: '😛 Face with stuck-out tongue' },
      { id: 'smiley-46', imagePath: '/images/emojis/Smileys/😜 Winking face with stuck-out tongue.png', name: '😜 Winking face with stuck-out tongue' },
      { id: 'smiley-47', imagePath: '/images/emojis/Smileys/😝 Face with stuck-out tongue and squinting eyes.png', name: '😝 Face with stuck-out tongue and squinting eyes' },
      { id: 'smiley-48', imagePath: '/images/emojis/Smileys/😞 Disappointed face.png', name: '😞 Disappointed face' },
      { id: 'smiley-49', imagePath: '/images/emojis/Smileys/😟 Worried face.png', name: '😟 Worried face' },
      { id: 'smiley-50', imagePath: '/images/emojis/Smileys/😠 Angry face.png', name: '😠 Angry face' },
      { id: 'smiley-51', imagePath: '/images/emojis/Smileys/😡 Red angry face.png', name: '😡 Red angry face' },
      { id: 'smiley-52', imagePath: '/images/emojis/Smileys/😢 Crying face.png', name: '😢 Crying face' },
      { id: 'smiley-53', imagePath: '/images/emojis/Smileys/😣 Persevering face.png', name: '😣 Persevering face' },
      { id: 'smiley-54', imagePath: '/images/emojis/Smileys/😤 Face with steam from nose.png', name: '😤 Face with steam from nose' },
      { id: 'smiley-55', imagePath: '/images/emojis/Smileys/😥 Sad but relieved face.png', name: '😥 Sad but relieved face' },
      { id: 'smiley-56', imagePath: '/images/emojis/Smileys/😦 Frowning face with open mouth.png', name: '😦 Frowning face with open mouth' },
      { id: 'smiley-57', imagePath: '/images/emojis/Smileys/😧 Anguished face.png', name: '😧 Anguished face' },
      { id: 'smiley-58', imagePath: '/images/emojis/Smileys/😨 Fearful face.png', name: '😨 Fearful face' },
      { id: 'smiley-59', imagePath: '/images/emojis/Smileys/😩 Weary face.png', name: '😩 Weary face' },
      { id: 'smiley-60', imagePath: '/images/emojis/Smileys/😪 Sleepy face.png', name: '😪 Sleepy face' },
      { id: 'smiley-61', imagePath: '/images/emojis/Smileys/😫 Distraught face.png', name: '😫 Distraught face' },
      { id: 'smiley-62', imagePath: '/images/emojis/Smileys/😬 Grimacing face.png', name: '😬 Grimacing face' },
      { id: 'smiley-63', imagePath: '/images/emojis/Smileys/😭 Loudly crying face.png', name: '😭 Loudly crying face' },
      { id: 'smiley-64', imagePath: '/images/emojis/Smileys/😮 Surprised face with open mouth.png', name: '😮 Surprised face with open mouth' },
      { id: 'smiley-65', imagePath: '/images/emojis/Smileys/😯 Surprised face.png', name: '😯 Surprised face' },
      { id: 'smiley-66', imagePath: '/images/emojis/Smileys/😰 Anxious face with sweat.png', name: '😰 Anxious face with sweat' },
      { id: 'smiley-67', imagePath: '/images/emojis/Smileys/😱 Face screaming in fear.png', name: '😱 Face screaming in fear' },
      { id: 'smiley-68', imagePath: '/images/emojis/Smileys/😲 Astonished face.png', name: '😲 Astonished face' },
      { id: 'smiley-69', imagePath: '/images/emojis/Smileys/😳 Face with wide open eyes.png', name: '😳 Face with wide open eyes' },
      { id: 'smiley-70', imagePath: '/images/emojis/Smileys/😴 Sleeping face.png', name: '😴 Sleeping face' },
      { id: 'smiley-71', imagePath: '/images/emojis/Smileys/😵 Dizzy face.png', name: '😵 Dizzy face' },
      { id: 'smiley-72', imagePath: '/images/emojis/Smileys/😶 Face without mask.png', name: '😶 Face without mask' },
      { id: 'smiley-73', imagePath: '/images/emojis/Smileys/😷 Face with medical mask.png', name: '😷 Face with medical mask' },
      { id: 'smiley-74', imagePath: '/images/emojis/Smileys/😸 Grinning cat face.png', name: '😸 Grinning cat face' },
      { id: 'smiley-75', imagePath: '/images/emojis/Smileys/😹 Cat face with tears of joy.png', name: '😹 Cat face with tears of joy' },
      { id: 'smiley-76', imagePath: '/images/emojis/Smileys/😺 Happy cat face.png', name: '😺 Happy cat face' },
      { id: 'smiley-77', imagePath: '/images/emojis/Smileys/😻 Smiling cat face with heart-eyes.png', name: '😻 Smiling cat face with heart-eyes' },
      { id: 'smiley-78', imagePath: '/images/emojis/Smileys/😼 Smirking cat face.png', name: '😼 Smirking cat face' },
      { id: 'smiley-79', imagePath: '/images/emojis/Smileys/😽 Kissing cat face.png', name: '😽 Kissing cat face' },
      { id: 'smiley-80', imagePath: '/images/emojis/Smileys/😾 Pouting cat face.png', name: '😾 Pouting cat face' },
      { id: 'smiley-81', imagePath: '/images/emojis/Smileys/😿 Crying cat face.png', name: '😿 Crying cat face' },
      { id: 'smiley-82', imagePath: '/images/emojis/Smileys/🙀 Cat face screaming in fear.png', name: '🙀 Cat face screaming in fear' },
      { id: 'smiley-83', imagePath: '/images/emojis/Smileys/🙁 Slightly frowning face.png', name: '🙁 Slightly frowning face' },
      { id: 'smiley-84', imagePath: '/images/emojis/Smileys/🙂 Slightly smiling face.png', name: '🙂 Slightly smiling face' },
      { id: 'smiley-85', imagePath: '/images/emojis/Smileys/🙂‍↔️ Head shaking horizontally.png', name: '🙂‍↔️ Head shaking horizontally' },
      { id: 'smiley-86', imagePath: '/images/emojis/Smileys/🙂‍↕️ Head shaking vertically.png', name: '🙂‍↕️ Head shaking vertically' },
      { id: 'smiley-87', imagePath: '/images/emojis/Smileys/🙃 Upside-down face.png', name: '🙃 Upside-down face' },
      { id: 'smiley-88', imagePath: '/images/emojis/Smileys/🙄 Face with rolling eyes.png', name: '🙄 Face with rolling eyes' },
      { id: 'smiley-89', imagePath: '/images/emojis/Smileys/🤐 Face with a zip mouth.png', name: '🤐 Face with a zip mouth' },
      { id: 'smiley-90', imagePath: '/images/emojis/Smileys/🤑 Money-mouth face.png', name: '🤑 Money-mouth face' },
      { id: 'smiley-91', imagePath: '/images/emojis/Smileys/🤒 Face with thermometer.png', name: '🤒 Face with thermometer' },
      { id: 'smiley-92', imagePath: '/images/emojis/Smileys/🤔 Thinking face.png', name: '🤔 Thinking face' },
      { id: 'smiley-93', imagePath: '/images/emojis/Smileys/🤕 Face with head-bandage.png', name: '🤕 Face with head-bandage' },
      { id: 'smiley-94', imagePath: '/images/emojis/Smileys/🤖 Robot face.png', name: '🤖 Robot face' },
      { id: 'smiley-95', imagePath: '/images/emojis/Smileys/🤗 Hugging face.png', name: '🤗 Hugging face' },
      { id: 'smiley-96', imagePath: '/images/emojis/Smileys/🤠 Cowboy face.png', name: '🤠 Cowboy face' },
      { id: 'smiley-97', imagePath: '/images/emojis/Smileys/🤡 Clown face.png', name: '🤡 Clown face' },
      { id: 'smiley-98', imagePath: '/images/emojis/Smileys/🤢 Nauseated face.png', name: '🤢 Nauseated face' },
      { id: 'smiley-99', imagePath: '/images/emojis/Smileys/🤣 Rolling on the floor laughing face.png', name: '🤣 Rolling on the floor laughing face' },
      { id: 'smiley-100', imagePath: '/images/emojis/Smileys/🤤 Drooling face.png', name: '🤤 Drooling face' },
      { id: 'smiley-101', imagePath: '/images/emojis/Smileys/🤥 Lying face.png', name: '🤥 Lying face' },
      { id: 'smiley-102', imagePath: '/images/emojis/Smileys/🤨 Face with raised eyebrow.png', name: '🤨 Face with raised eyebrow' },
      { id: 'smiley-103', imagePath: '/images/emojis/Smileys/🤩 Face with starry eyes.png', name: '🤩 Face with starry eyes' },
      { id: 'smiley-104', imagePath: '/images/emojis/Smileys/🤪 Goofy face.png', name: '🤪 Goofy face' },
      { id: 'smiley-105', imagePath: '/images/emojis/Smileys/🤫 Shushing face.png', name: '🤫 Shushing face' },
      { id: 'smiley-106', imagePath: '/images/emojis/Smileys/🤬 Face with symbols over mouth.png', name: '🤬 Face with symbols over mouth' },
      { id: 'smiley-107', imagePath: '/images/emojis/Smileys/🤭 Face with hand over mouth and smiling eyes.png', name: '🤭 Face with hand over mouth and smiling eyes' },
      { id: 'smiley-108', imagePath: '/images/emojis/Smileys/🤮 Vomiting face.png', name: '🤮 Vomiting face' },
      { id: 'smiley-109', imagePath: '/images/emojis/Smileys/🤯 Exploding head.png', name: '🤯 Exploding head' },
      { id: 'smiley-110', imagePath: '/images/emojis/Smileys/🥰 Smiling face with hearts.png', name: '🥰 Smiling face with hearts' },
      { id: 'smiley-111', imagePath: '/images/emojis/Smileys/🥱 Yawning face.png', name: '🥱 Yawning face' },
      { id: 'smiley-112', imagePath: '/images/emojis/Smileys/🥲 Smiling face with tear.png', name: '🥲 Smiling face with tear' },
      { id: 'smiley-113', imagePath: '/images/emojis/Smileys/🥳 Party face.png', name: '🥳 Party face' },
      { id: 'smiley-114', imagePath: '/images/emojis/Smileys/🥴 Woozy face.png', name: '🥴 Woozy face' },
      { id: 'smiley-115', imagePath: '/images/emojis/Smileys/🥵 Hot face.png', name: '🥵 Hot face' },
      { id: 'smiley-116', imagePath: '/images/emojis/Smileys/🥶 Cold face.png', name: '🥶 Cold face' },
      { id: 'smiley-117', imagePath: '/images/emojis/Smileys/🥸 Disguised face.png', name: '🥸 Disguised face' },
      { id: 'smiley-118', imagePath: '/images/emojis/Smileys/🥹 Smiling face holding back tears.png', name: '🥹 Smiling face holding back tears' },
      { id: 'smiley-119', imagePath: '/images/emojis/Smileys/🥺 Pleading face.png', name: '🥺 Pleading face' },
      { id: 'smiley-120', imagePath: '/images/emojis/Smileys/🧐 Face with monocle.png', name: '🧐 Face with monocle' },
      { id: 'smiley-121', imagePath: '/images/emojis/Smileys/🫠 Melting face.png', name: '🫠 Melting face' },
      { id: 'smiley-122', imagePath: '/images/emojis/Smileys/🫡 Saluting face.png', name: '🫡 Saluting face' },
      { id: 'smiley-123', imagePath: '/images/emojis/Smileys/🫢 Face with open eyes and hand over mouth.png', name: '🫢 Face with open eyes and hand over mouth' },
      { id: 'smiley-124', imagePath: '/images/emojis/Smileys/🫣 Face with peeking eye.png', name: '🫣 Face with peeking eye' },
      { id: 'smiley-125', imagePath: '/images/emojis/Smileys/🫤 Face with diagonal mouth.png', name: '🫤 Face with diagonal mouth' },
      { id: 'smiley-126', imagePath: '/images/emojis/Smileys/🫥 Dotted line face.png', name: '🫥 Dotted line face' },
      { id: 'smiley-127', imagePath: '/images/emojis/Smileys/🫨 Shaking face.png', name: '🫨 Shaking face' },
    ],
  },
  {
    name: 'People',
    items: [
      { id: 'people-1', imagePath: '/images/emojis/People/Artist_Light_Female.png', name: 'Artist_Light_Female' },
      { id: 'people-2', imagePath: '/images/emojis/People/Artist_Light_Male.png', name: 'Artist_Light_Male' },
      { id: 'people-3', imagePath: '/images/emojis/People/Artist_Light_Neutral.png', name: 'Artist_Light_Neutral' },
      { id: 'people-4', imagePath: '/images/emojis/People/Astronaut_Light_Female.png', name: 'Astronaut_Light_Female' },
      { id: 'people-5', imagePath: '/images/emojis/People/Astronaut_Light_Male.png', name: 'Astronaut_Light_Male' },
      { id: 'people-6', imagePath: '/images/emojis/People/Astronaut_Light_Neutral.png', name: 'Astronaut_Light_Neutral' },
      { id: 'people-7', imagePath: '/images/emojis/People/Cook_Light_Female.png', name: 'Cook_Light_Female' },
      { id: 'people-8', imagePath: '/images/emojis/People/Cook_Light_Male.png', name: 'Cook_Light_Male' },
      { id: 'people-9', imagePath: '/images/emojis/People/Cook_Light_Neutral.png', name: 'Cook_Light_Neutral' },
      { id: 'people-10', imagePath: '/images/emojis/People/Factory worker_Light_Female.png', name: 'Factory worker_Light_Female' },
      { id: 'people-11', imagePath: '/images/emojis/People/Factory worker_Light_Male.png', name: 'Factory worker_Light_Male' },
      { id: 'people-12', imagePath: '/images/emojis/People/Factory worker_Light_Neutral.png', name: 'Factory worker_Light_Neutral' },
      { id: 'people-13', imagePath: '/images/emojis/People/Farmer_Light_Female.png', name: 'Farmer_Light_Female' },
      { id: 'people-14', imagePath: '/images/emojis/People/Farmer_Light_Male.png', name: 'Farmer_Light_Male' },
      { id: 'people-15', imagePath: '/images/emojis/People/Farmer_Light_Neutral.png', name: 'Farmer_Light_Neutral' },
      { id: 'people-16', imagePath: '/images/emojis/People/Firefighter_Light_Female.png', name: 'Firefighter_Light_Female' },
      { id: 'people-17', imagePath: '/images/emojis/People/Firefighter_Light_Male.png', name: 'Firefighter_Light_Male' },
      { id: 'people-18', imagePath: '/images/emojis/People/Firefighter_Light_Neutral.png', name: 'Firefighter_Light_Neutral' },
      { id: 'people-19', imagePath: '/images/emojis/People/Health worker_Light_Female.png', name: 'Health worker_Light_Female' },
      { id: 'people-20', imagePath: '/images/emojis/People/Health worker_Light_Male.png', name: 'Health worker_Light_Male' },
      { id: 'people-21', imagePath: '/images/emojis/People/Health worker_Light_Neutral.png', name: 'Health worker_Light_Neutral' },
      { id: 'people-22', imagePath: '/images/emojis/People/Judge_Light_Female.png', name: 'Judge_Light_Female' },
      { id: 'people-23', imagePath: '/images/emojis/People/Judge_Light_Male.png', name: 'Judge_Light_Male' },
      { id: 'people-24', imagePath: '/images/emojis/People/Judge_Light_Neutral.png', name: 'Judge_Light_Neutral' },
      { id: 'people-25', imagePath: '/images/emojis/People/Mechanic_Light_Female.png', name: 'Mechanic_Light_Female' },
      { id: 'people-26', imagePath: '/images/emojis/People/Mechanic_Light_Male.png', name: 'Mechanic_Light_Male' },
      { id: 'people-27', imagePath: '/images/emojis/People/Mechanic_Light_Neutral.png', name: 'Mechanic_Light_Neutral' },
      { id: 'people-28', imagePath: '/images/emojis/People/Mx Claus_Light_Female.png', name: 'Mx Claus_Light_Female' },
      { id: 'people-29', imagePath: '/images/emojis/People/Mx Claus_Light_Male.png', name: 'Mx Claus_Light_Male' },
      { id: 'people-30', imagePath: '/images/emojis/People/Mx Claus_Light_Neutral.png', name: 'Mx Claus_Light_Neutral' },
      { id: 'people-31', imagePath: '/images/emojis/People/Office worker_Light_Female.png', name: 'Office worker_Light_Female' },
      { id: 'people-32', imagePath: '/images/emojis/People/Office worker_Light_Male.png', name: 'Office worker_Light_Male' },
      { id: 'people-33', imagePath: '/images/emojis/People/Office worker_Light_Neutral.png', name: 'Office worker_Light_Neutral' },
      { id: 'people-34', imagePath: '/images/emojis/People/Person feeding baby_Light_Female.png', name: 'Person feeding baby_Light_Female' },
      { id: 'people-35', imagePath: '/images/emojis/People/Person feeding baby_Light_Male.png', name: 'Person feeding baby_Light_Male' },
      { id: 'people-36', imagePath: '/images/emojis/People/Person feeding baby_Light_Neutral.png', name: 'Person feeding baby_Light_Neutral' },
      { id: 'people-37', imagePath: '/images/emojis/People/Person with curly hair_Light_Female.png', name: 'Person with curly hair_Light_Female' },
      { id: 'people-38', imagePath: '/images/emojis/People/Person with curly hair_Light_Male.png', name: 'Person with curly hair_Light_Male' },
      { id: 'people-39', imagePath: '/images/emojis/People/Person with curly hair_Light_Neutral.png', name: 'Person with curly hair_Light_Neutral' },
      { id: 'people-40', imagePath: '/images/emojis/People/Person with no hair_Light_Female.png', name: 'Person with no hair_Light_Female' },
      { id: 'people-41', imagePath: '/images/emojis/People/Person with no hair_Light_Male.png', name: 'Person with no hair_Light_Male' },
      { id: 'people-42', imagePath: '/images/emojis/People/Person with no hair_Light_Neutral.png', name: 'Person with no hair_Light_Neutral' },
      { id: 'people-43', imagePath: '/images/emojis/People/Person with red hair_Light_Female.png', name: 'Person with red hair_Light_Female' },
      { id: 'people-44', imagePath: '/images/emojis/People/Person with red hair_Light_Male.png', name: 'Person with red hair_Light_Male' },
      { id: 'people-45', imagePath: '/images/emojis/People/Person with red hair_Light_Neutral.png', name: 'Person with red hair_Light_Neutral' },
      { id: 'people-46', imagePath: '/images/emojis/People/Person with white hair_Light_Female.png', name: 'Person with white hair_Light_Female' },
      { id: 'people-47', imagePath: '/images/emojis/People/Person with white hair_Light_Male.png', name: 'Person with white hair_Light_Male' },
      { id: 'people-48', imagePath: '/images/emojis/People/Person with white hair_Light_Neutral.png', name: 'Person with white hair_Light_Neutral' },
      { id: 'people-49', imagePath: '/images/emojis/People/Pilot_Light_Female.png', name: 'Pilot_Light_Female' },
      { id: 'people-50', imagePath: '/images/emojis/People/Pilot_Light_Male.png', name: 'Pilot_Light_Male' },
      { id: 'people-51', imagePath: '/images/emojis/People/Pilot_Light_Neutral.png', name: 'Pilot_Light_Neutral' },
      { id: 'people-52', imagePath: '/images/emojis/People/Scientist_Light_Female.png', name: 'Scientist_Light_Female' },
      { id: 'people-53', imagePath: '/images/emojis/People/Scientist_Light_Male.png', name: 'Scientist_Light_Male' },
      { id: 'people-54', imagePath: '/images/emojis/People/Scientist_Light_Neutral.png', name: 'Scientist_Light_Neutral' },
      { id: 'people-55', imagePath: '/images/emojis/People/Singer_Light_Female.png', name: 'Singer_Light_Female' },
      { id: 'people-56', imagePath: '/images/emojis/People/Singer_Light_Male.png', name: 'Singer_Light_Male' },
      { id: 'people-57', imagePath: '/images/emojis/People/Singer_Light_Neutral.png', name: 'Singer_Light_Neutral' },
      { id: 'people-58', imagePath: '/images/emojis/People/Student_Light_Female.png', name: 'Student_Light_Female' },
      { id: 'people-59', imagePath: '/images/emojis/People/Student_Light_Male.png', name: 'Student_Light_Male' },
      { id: 'people-60', imagePath: '/images/emojis/People/Student_Light_Neutral.png', name: 'Student_Light_Neutral' },
      { id: 'people-61', imagePath: '/images/emojis/People/Teacher_Light_Female.png', name: 'Teacher_Light_Female' },
      { id: 'people-62', imagePath: '/images/emojis/People/Teacher_Light_Male.png', name: 'Teacher_Light_Male' },
      { id: 'people-63', imagePath: '/images/emojis/People/Teacher_Light_Neutral.png', name: 'Teacher_Light_Neutral' },
      { id: 'people-64', imagePath: '/images/emojis/People/Technologist_Light_Female.png', name: 'Technologist_Light_Female' },
      { id: 'people-65', imagePath: '/images/emojis/People/Technologist_Light_Male.png', name: 'Technologist_Light_Male' },
      { id: 'people-66', imagePath: '/images/emojis/People/Technologist_Light_Neutral.png', name: 'Technologist_Light_Neutral' },
      { id: 'people-67', imagePath: '/images/emojis/People/👦 Child_Light_Female.png', name: '👦 Child_Light_Female' },
      { id: 'people-68', imagePath: '/images/emojis/People/👦 Child_Light_Male.png', name: '👦 Child_Light_Male' },
      { id: 'people-69', imagePath: '/images/emojis/People/👦 Child_Light_Neutral.png', name: '👦 Child_Light_Neutral' },
      { id: 'people-70', imagePath: '/images/emojis/People/👮 Police officer_Light_Female.png', name: '👮 Police officer_Light_Female' },
      { id: 'people-71', imagePath: '/images/emojis/People/👮 Police officer_Light_Male.png', name: '👮 Police officer_Light_Male' },
      { id: 'people-72', imagePath: '/images/emojis/People/👮 Police officer_Light_Neutral.png', name: '👮 Police officer_Light_Neutral' },
      { id: 'people-73', imagePath: '/images/emojis/People/👰 Person with veil_Light_Female.png', name: '👰 Person with veil_Light_Female' },
      { id: 'people-74', imagePath: '/images/emojis/People/👰 Person with veil_Light_Male.png', name: '👰 Person with veil_Light_Male' },
      { id: 'people-75', imagePath: '/images/emojis/People/👰 Person with veil_Light_Neutral.png', name: '👰 Person with veil_Light_Neutral' },
      { id: 'people-76', imagePath: '/images/emojis/People/👱 Person with blond hair_Light_Female.png', name: '👱 Person with blond hair_Light_Female' },
      { id: 'people-77', imagePath: '/images/emojis/People/👱 Person with blond hair_Light_Male.png', name: '👱 Person with blond hair_Light_Male' },
      { id: 'people-78', imagePath: '/images/emojis/People/👱 Person with blond hair_Light_Neutral.png', name: '👱 Person with blond hair_Light_Neutral' },
      { id: 'people-79', imagePath: '/images/emojis/People/👲 Man with Chinese cap_Light.png', name: '👲 Man with Chinese cap_Light' },
      { id: 'people-80', imagePath: '/images/emojis/People/👳 Person with turban_Light_Female.png', name: '👳 Person with turban_Light_Female' },
      { id: 'people-81', imagePath: '/images/emojis/People/👳 Person with turban_Light_Male.png', name: '👳 Person with turban_Light_Male' },
      { id: 'people-82', imagePath: '/images/emojis/People/👳 Person with turban_Light_Neutral.png', name: '👳 Person with turban_Light_Neutral' },
      { id: 'people-83', imagePath: '/images/emojis/People/👶 Baby_Light.png', name: '👶 Baby_Light' },
      { id: 'people-84', imagePath: '/images/emojis/People/👷 Construction worker_Light_Female.png', name: '👷 Construction worker_Light_Female' },
      { id: 'people-85', imagePath: '/images/emojis/People/👷 Construction worker_Light_Male.png', name: '👷 Construction worker_Light_Male' },
      { id: 'people-86', imagePath: '/images/emojis/People/👷 Construction worker_Light_Neutral.png', name: '👷 Construction worker_Light_Neutral' },
      { id: 'people-87', imagePath: '/images/emojis/People/👼 Baby angel_Light.png', name: '👼 Baby angel_Light' },
      { id: 'people-88', imagePath: '/images/emojis/People/💁 Information desk attendant_Light_Female.png', name: '💁 Information desk attendant_Light_Female' },
      { id: 'people-89', imagePath: '/images/emojis/People/💁 Information desk attendant_Light_Male.png', name: '💁 Information desk attendant_Light_Male' },
      { id: 'people-90', imagePath: '/images/emojis/People/💁 Information desk attendant_Light_Neutral.png', name: '💁 Information desk attendant_Light_Neutral' },
      { id: 'people-91', imagePath: '/images/emojis/People/💂 Guard_Light_Female.png', name: '💂 Guard_Light_Female' },
      { id: 'people-92', imagePath: '/images/emojis/People/💂 Guard_Light_Male.png', name: '💂 Guard_Light_Male' },
      { id: 'people-93', imagePath: '/images/emojis/People/💂 Guard_Light_Neutral.png', name: '💂 Guard_Light_Neutral' },
      { id: 'people-94', imagePath: '/images/emojis/People/💆 Person getting a head massage_Light_Female.png', name: '💆 Person getting a head massage_Light_Female' },
      { id: 'people-95', imagePath: '/images/emojis/People/💆 Person getting a head massage_Light_Male.png', name: '💆 Person getting a head massage_Light_Male' },
      { id: 'people-96', imagePath: '/images/emojis/People/💆 Person getting a head massage_Light_Neutral.png', name: '💆 Person getting a head massage_Light_Neutral' },
      { id: 'people-97', imagePath: '/images/emojis/People/💇 Person getting a haircut_Light_Female.png', name: '💇 Person getting a haircut_Light_Female' },
      { id: 'people-98', imagePath: '/images/emojis/People/💇 Person getting a haircut_Light_Male.png', name: '💇 Person getting a haircut_Light_Male' },
      { id: 'people-99', imagePath: '/images/emojis/People/💇 Person getting a haircut_Light_Neutral.png', name: '💇 Person getting a haircut_Light_Neutral' },
      { id: 'people-100', imagePath: '/images/emojis/People/🕵️ Detective_Light_Female.png', name: '🕵️ Detective_Light_Female' },
      { id: 'people-101', imagePath: '/images/emojis/People/🕵️ Detective_Light_Male.png', name: '🕵️ Detective_Light_Male' },
      { id: 'people-102', imagePath: '/images/emojis/People/🕵️ Detective_Light_Neutral.png', name: '🕵️ Detective_Light_Neutral' },
      { id: 'people-103', imagePath: '/images/emojis/People/🙅 Person gesturing no_Light_Female.png', name: '🙅 Person gesturing no_Light_Female' },
      { id: 'people-104', imagePath: '/images/emojis/People/🙅 Person gesturing no_Light_Male.png', name: '🙅 Person gesturing no_Light_Male' },
      { id: 'people-105', imagePath: '/images/emojis/People/🙅 Person gesturing no_Light_Neutral.png', name: '🙅 Person gesturing no_Light_Neutral' },
      { id: 'people-106', imagePath: '/images/emojis/People/🙆 Person gesturing OK_Light_Female.png', name: '🙆 Person gesturing OK_Light_Female' },
      { id: 'people-107', imagePath: '/images/emojis/People/🙆 Person gesturing OK_Light_Male.png', name: '🙆 Person gesturing OK_Light_Male' },
      { id: 'people-108', imagePath: '/images/emojis/People/🙆 Person gesturing OK_Light_Neutral.png', name: '🙆 Person gesturing OK_Light_Neutral' },
      { id: 'people-109', imagePath: '/images/emojis/People/🙇 Person bowing_Light_Female.png', name: '🙇 Person bowing_Light_Female' },
      { id: 'people-110', imagePath: '/images/emojis/People/🙇 Person bowing_Light_Male.png', name: '🙇 Person bowing_Light_Male' },
      { id: 'people-111', imagePath: '/images/emojis/People/🙇 Person bowing_Light_Neutral.png', name: '🙇 Person bowing_Light_Neutral' },
      { id: 'people-112', imagePath: '/images/emojis/People/🙋 Person raising one hand_Light_Female.png', name: '🙋 Person raising one hand_Light_Female' },
      { id: 'people-113', imagePath: '/images/emojis/People/🙋 Person raising one hand_Light_Male.png', name: '🙋 Person raising one hand_Light_Male' },
      { id: 'people-114', imagePath: '/images/emojis/People/🙋 Person raising one hand_Light_Neutral.png', name: '🙋 Person raising one hand_Light_Neutral' },
      { id: 'people-115', imagePath: '/images/emojis/People/🙍 Person frowning_Light_Female.png', name: '🙍 Person frowning_Light_Female' },
      { id: 'people-116', imagePath: '/images/emojis/People/🙍 Person frowning_Light_Male.png', name: '🙍 Person frowning_Light_Male' },
      { id: 'people-117', imagePath: '/images/emojis/People/🙍 Person frowning_Light_Neutral.png', name: '🙍 Person frowning_Light_Neutral' },
      { id: 'people-118', imagePath: '/images/emojis/People/🙎 Person pouting_Light_Female.png', name: '🙎 Person pouting_Light_Female' },
      { id: 'people-119', imagePath: '/images/emojis/People/🙎 Person pouting_Light_Male.png', name: '🙎 Person pouting_Light_Male' },
      { id: 'people-120', imagePath: '/images/emojis/People/🙎 Person pouting_Light_Neutral.png', name: '🙎 Person pouting_Light_Neutral' },
      { id: 'people-121', imagePath: '/images/emojis/People/🤦 Person facepalming_Light_Female.png', name: '🤦 Person facepalming_Light_Female' },
      { id: 'people-122', imagePath: '/images/emojis/People/🤦 Person facepalming_Light_Male.png', name: '🤦 Person facepalming_Light_Male' },
      { id: 'people-123', imagePath: '/images/emojis/People/🤦 Person facepalming_Light_Neutral.png', name: '🤦 Person facepalming_Light_Neutral' },
      { id: 'people-124', imagePath: '/images/emojis/People/🤱 Breastfeeding_Light.png', name: '🤱 Breastfeeding_Light' },
      { id: 'people-125', imagePath: '/images/emojis/People/🤵 Person in tuxedo_Light_Female.png', name: '🤵 Person in tuxedo_Light_Female' },
      { id: 'people-126', imagePath: '/images/emojis/People/🤵 Person in tuxedo_Light_Male.png', name: '🤵 Person in tuxedo_Light_Male' },
      { id: 'people-127', imagePath: '/images/emojis/People/🤵 Person in tuxedo_Light_Neutral.png', name: '🤵 Person in tuxedo_Light_Neutral' },
      { id: 'people-128', imagePath: '/images/emojis/People/🤷 Person shrugging_Light_Female.png', name: '🤷 Person shrugging_Light_Female' },
      { id: 'people-129', imagePath: '/images/emojis/People/🤷 Person shrugging_Light_Male.png', name: '🤷 Person shrugging_Light_Male' },
      { id: 'people-130', imagePath: '/images/emojis/People/🤷 Person shrugging_Light_Neutral.png', name: '🤷 Person shrugging_Light_Neutral' },
      { id: 'people-131', imagePath: '/images/emojis/People/🥷 Ninja_Light.png', name: '🥷 Ninja_Light' },
      { id: 'people-132', imagePath: '/images/emojis/People/🦸 Superhero_Light_Female.png', name: '🦸 Superhero_Light_Female' },
      { id: 'people-133', imagePath: '/images/emojis/People/🦸 Superhero_Light_Male.png', name: '🦸 Superhero_Light_Male' },
      { id: 'people-134', imagePath: '/images/emojis/People/🦸 Superhero_Light_Neutral.png', name: '🦸 Superhero_Light_Neutral' },
      { id: 'people-135', imagePath: '/images/emojis/People/🦹 Supervillain_Light_Female.png', name: '🦹 Supervillain_Light_Female' },
      { id: 'people-136', imagePath: '/images/emojis/People/🦹 Supervillain_Light_Male.png', name: '🦹 Supervillain_Light_Male' },
      { id: 'people-137', imagePath: '/images/emojis/People/🦹 Supervillain_Light_Neutral.png', name: '🦹 Supervillain_Light_Neutral' },
      { id: 'people-138', imagePath: '/images/emojis/People/🧌 Troll.png', name: '🧌 Troll' },
      { id: 'people-139', imagePath: '/images/emojis/People/🧏 Deaf person_Light_Female.png', name: '🧏 Deaf person_Light_Female' },
      { id: 'people-140', imagePath: '/images/emojis/People/🧏 Deaf person_Light_Male.png', name: '🧏 Deaf person_Light_Male' },
      { id: 'people-141', imagePath: '/images/emojis/People/🧏 Deaf person_Light_Neutral.png', name: '🧏 Deaf person_Light_Neutral' },
      { id: 'people-142', imagePath: '/images/emojis/People/🧑 Adult_Light_Female.png', name: '🧑 Adult_Light_Female' },
      { id: 'people-143', imagePath: '/images/emojis/People/🧑 Adult_Light_Male.png', name: '🧑 Adult_Light_Male' },
      { id: 'people-144', imagePath: '/images/emojis/People/🧑 Adult_Light_Neutral.png', name: '🧑 Adult_Light_Neutral' },
      { id: 'people-145', imagePath: '/images/emojis/People/🧓 Old person_Light_Female.png', name: '🧓 Old person_Light_Female' },
      { id: 'people-146', imagePath: '/images/emojis/People/🧓 Old person_Light_Male.png', name: '🧓 Old person_Light_Male' },
      { id: 'people-147', imagePath: '/images/emojis/People/🧓 Old person_Light_Neutral.png', name: '🧓 Old person_Light_Neutral' },
      { id: 'people-148', imagePath: '/images/emojis/People/🧔 Bearded person_Light_Female.png', name: '🧔 Bearded person_Light_Female' },
      { id: 'people-149', imagePath: '/images/emojis/People/🧔 Bearded person_Light_Male.png', name: '🧔 Bearded person_Light_Male' },
      { id: 'people-150', imagePath: '/images/emojis/People/🧔 Bearded person_Light_Neutral.png', name: '🧔 Bearded person_Light_Neutral' },
      { id: 'people-151', imagePath: '/images/emojis/People/🧕 Woman with headscarf_Light.png', name: '🧕 Woman with headscarf_Light' },
      { id: 'people-152', imagePath: '/images/emojis/People/🧖 Person in a sauna_Light_Female.png', name: '🧖 Person in a sauna_Light_Female' },
      { id: 'people-153', imagePath: '/images/emojis/People/🧖 Person in a sauna_Light_Male.png', name: '🧖 Person in a sauna_Light_Male' },
      { id: 'people-154', imagePath: '/images/emojis/People/🧖 Person in a sauna_Light_Neutral.png', name: '🧖 Person in a sauna_Light_Neutral' },
      { id: 'people-155', imagePath: '/images/emojis/People/🧙 Sorcerer_Light_Female.png', name: '🧙 Sorcerer_Light_Female' },
      { id: 'people-156', imagePath: '/images/emojis/People/🧙 Sorcerer_Light_Male.png', name: '🧙 Sorcerer_Light_Male' },
      { id: 'people-157', imagePath: '/images/emojis/People/🧙 Sorcerer_Light_Neutral.png', name: '🧙 Sorcerer_Light_Neutral' },
      { id: 'people-158', imagePath: '/images/emojis/People/🧚 Fairy_Light_Female.png', name: '🧚 Fairy_Light_Female' },
      { id: 'people-159', imagePath: '/images/emojis/People/🧚 Fairy_Light_Male.png', name: '🧚 Fairy_Light_Male' },
      { id: 'people-160', imagePath: '/images/emojis/People/🧚 Fairy_Light_Neutral.png', name: '🧚 Fairy_Light_Neutral' },
      { id: 'people-161', imagePath: '/images/emojis/People/🧛 Vampire_Light_Female.png', name: '🧛 Vampire_Light_Female' },
      { id: 'people-162', imagePath: '/images/emojis/People/🧛 Vampire_Light_Male.png', name: '🧛 Vampire_Light_Male' },
      { id: 'people-163', imagePath: '/images/emojis/People/🧛 Vampire_Light_Neutral.png', name: '🧛 Vampire_Light_Neutral' },
      { id: 'people-164', imagePath: '/images/emojis/People/🧜 Merperson_Light_Female.png', name: '🧜 Merperson_Light_Female' },
      { id: 'people-165', imagePath: '/images/emojis/People/🧜 Merperson_Light_Male.png', name: '🧜 Merperson_Light_Male' },
      { id: 'people-166', imagePath: '/images/emojis/People/🧜 Merperson_Light_Neutral.png', name: '🧜 Merperson_Light_Neutral' },
      { id: 'people-167', imagePath: '/images/emojis/People/🧝 Elf_Light_Female.png', name: '🧝 Elf_Light_Female' },
      { id: 'people-168', imagePath: '/images/emojis/People/🧝 Elf_Light_Male.png', name: '🧝 Elf_Light_Male' },
      { id: 'people-169', imagePath: '/images/emojis/People/🧝 Elf_Light_Neutral.png', name: '🧝 Elf_Light_Neutral' },
      { id: 'people-170', imagePath: '/images/emojis/People/🧞 Genie_Neutral.png', name: '🧞 Genie_Neutral' },
      { id: 'people-171', imagePath: '/images/emojis/People/🧟 Zombie_Neutral.png', name: '🧟 Zombie_Neutral' },
      { id: 'people-172', imagePath: '/images/emojis/People/🫄 Pregnant person_Light_Female.png', name: '🫄 Pregnant person_Light_Female' },
      { id: 'people-173', imagePath: '/images/emojis/People/🫄 Pregnant person_Light_Male.png', name: '🫄 Pregnant person_Light_Male' },
      { id: 'people-174', imagePath: '/images/emojis/People/🫄 Pregnant person_Light_Neutral.png', name: '🫄 Pregnant person_Light_Neutral' },
      { id: 'people-175', imagePath: '/images/emojis/People/🫅 Person with crown_Light_Female.png', name: '🫅 Person with crown_Light_Female' },
      { id: 'people-176', imagePath: '/images/emojis/People/🫅 Person with crown_Light_Male.png', name: '🫅 Person with crown_Light_Male' },
      { id: 'people-177', imagePath: '/images/emojis/People/🫅 Person with crown_Light_Neutral.png', name: '🫅 Person with crown_Light_Neutral' },
    ],
  },
  {
    name: 'More People',
    items: [
      { id: 'more-people-1', imagePath: '/images/emojis/More People/Couple kissing_Yellow_Yellow.png', name: 'Couple kissing_Yellow_Yellow' },
      { id: 'more-people-2', imagePath: '/images/emojis/More People/Couple with heart_Yellow_Yellow.png', name: 'Couple with heart_Yellow_Yellow' },
      { id: 'more-people-3', imagePath: '/images/emojis/More People/DEPRECATED Family-1.png', name: 'DEPRECATED Family-1' },
      { id: 'more-people-4', imagePath: '/images/emojis/More People/DEPRECATED Family-10.png', name: 'DEPRECATED Family-10' },
      { id: 'more-people-5', imagePath: '/images/emojis/More People/DEPRECATED Family-11.png', name: 'DEPRECATED Family-11' },
      { id: 'more-people-6', imagePath: '/images/emojis/More People/DEPRECATED Family-12.png', name: 'DEPRECATED Family-12' },
      { id: 'more-people-7', imagePath: '/images/emojis/More People/DEPRECATED Family-13.png', name: 'DEPRECATED Family-13' },
      { id: 'more-people-8', imagePath: '/images/emojis/More People/DEPRECATED Family-14.png', name: 'DEPRECATED Family-14' },
      { id: 'more-people-9', imagePath: '/images/emojis/More People/DEPRECATED Family-15.png', name: 'DEPRECATED Family-15' },
      { id: 'more-people-10', imagePath: '/images/emojis/More People/DEPRECATED Family-16.png', name: 'DEPRECATED Family-16' },
      { id: 'more-people-11', imagePath: '/images/emojis/More People/DEPRECATED Family-17.png', name: 'DEPRECATED Family-17' },
      { id: 'more-people-12', imagePath: '/images/emojis/More People/DEPRECATED Family-18.png', name: 'DEPRECATED Family-18' },
      { id: 'more-people-13', imagePath: '/images/emojis/More People/DEPRECATED Family-19.png', name: 'DEPRECATED Family-19' },
      { id: 'more-people-14', imagePath: '/images/emojis/More People/DEPRECATED Family-2.png', name: 'DEPRECATED Family-2' },
      { id: 'more-people-15', imagePath: '/images/emojis/More People/DEPRECATED Family-20.png', name: 'DEPRECATED Family-20' },
      { id: 'more-people-16', imagePath: '/images/emojis/More People/DEPRECATED Family-21.png', name: 'DEPRECATED Family-21' },
      { id: 'more-people-17', imagePath: '/images/emojis/More People/DEPRECATED Family-22.png', name: 'DEPRECATED Family-22' },
      { id: 'more-people-18', imagePath: '/images/emojis/More People/DEPRECATED Family-23.png', name: 'DEPRECATED Family-23' },
      { id: 'more-people-19', imagePath: '/images/emojis/More People/DEPRECATED Family-24.png', name: 'DEPRECATED Family-24' },
      { id: 'more-people-20', imagePath: '/images/emojis/More People/DEPRECATED Family-3.png', name: 'DEPRECATED Family-3' },
      { id: 'more-people-21', imagePath: '/images/emojis/More People/DEPRECATED Family-4.png', name: 'DEPRECATED Family-4' },
      { id: 'more-people-22', imagePath: '/images/emojis/More People/DEPRECATED Family-5.png', name: 'DEPRECATED Family-5' },
      { id: 'more-people-23', imagePath: '/images/emojis/More People/DEPRECATED Family-6.png', name: 'DEPRECATED Family-6' },
      { id: 'more-people-24', imagePath: '/images/emojis/More People/DEPRECATED Family-7.png', name: 'DEPRECATED Family-7' },
      { id: 'more-people-25', imagePath: '/images/emojis/More People/DEPRECATED Family-8.png', name: 'DEPRECATED Family-8' },
      { id: 'more-people-26', imagePath: '/images/emojis/More People/DEPRECATED Family-9.png', name: 'DEPRECATED Family-9' },
      { id: 'more-people-27', imagePath: '/images/emojis/More People/DEPRECATED Family.png', name: 'DEPRECATED Family' },
      { id: 'more-people-28', imagePath: '/images/emojis/More People/Man and woman kissing_Yellow_Yellow.png', name: 'Man and woman kissing_Yellow_Yellow' },
      { id: 'more-people-29', imagePath: '/images/emojis/More People/Man and woman with heart_Yellow_Yellow.png', name: 'Man and woman with heart_Yellow_Yellow' },
      { id: 'more-people-30', imagePath: '/images/emojis/More People/Two men kissing_Yellow_Yellow.png', name: 'Two men kissing_Yellow_Yellow' },
      { id: 'more-people-31', imagePath: '/images/emojis/More People/Two men with heart_Yellow_Yellow.png', name: 'Two men with heart_Yellow_Yellow' },
      { id: 'more-people-32', imagePath: '/images/emojis/More People/Two women kissing_Yellow_Yellow.png', name: 'Two women kissing_Yellow_Yellow' },
      { id: 'more-people-33', imagePath: '/images/emojis/More People/Two women with heart_Yellow_Yellow.png', name: 'Two women with heart_Yellow_Yellow' },
      { id: 'more-people-34', imagePath: '/images/emojis/More People/👫 Man and woman holding hands_Yellow_Yellow.png', name: '👫 Man and woman holding hands_Yellow_Yellow' },
      { id: 'more-people-35', imagePath: '/images/emojis/More People/👬 Two men holding hands_Yellow_Yellow.png', name: '👬 Two men holding hands_Yellow_Yellow' },
      { id: 'more-people-36', imagePath: '/images/emojis/More People/👭 Two women holding hands_Yellow_Yellow.png', name: '👭 Two women holding hands_Yellow_Yellow' },
    ],
  },
];



